// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage/storagepb/storage.proto

package storagepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreType int32

const (
	StoreType_LEVEL_DB  StoreType = 0
	StoreType_BIG_CACHE StoreType = 1
)

var StoreType_name = map[int32]string{
	0: "LEVEL_DB",
	1: "BIG_CACHE",
}

var StoreType_value = map[string]int32{
	"LEVEL_DB":  0,
	"BIG_CACHE": 1,
}

func (x StoreType) String() string {
	return proto.EnumName(StoreType_name, int32(x))
}

func (StoreType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{0}
}

type Connection struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 StoreType `protobuf:"varint,3,opt,name=type,proto3,enum=storage.StoreType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{0}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Connection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Connection) GetType() StoreType {
	if m != nil {
		return m.Type
	}
	return StoreType_LEVEL_DB
}

// open data store request
type OpenRqst struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Options              string   `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRqst) Reset()         { *m = OpenRqst{} }
func (m *OpenRqst) String() string { return proto.CompactTextString(m) }
func (*OpenRqst) ProtoMessage()    {}
func (*OpenRqst) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{1}
}

func (m *OpenRqst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRqst.Unmarshal(m, b)
}
func (m *OpenRqst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRqst.Marshal(b, m, deterministic)
}
func (m *OpenRqst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRqst.Merge(m, src)
}
func (m *OpenRqst) XXX_Size() int {
	return xxx_messageInfo_OpenRqst.Size(m)
}
func (m *OpenRqst) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRqst.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRqst proto.InternalMessageInfo

func (m *OpenRqst) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OpenRqst) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

type OpenRsp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRsp) Reset()         { *m = OpenRsp{} }
func (m *OpenRsp) String() string { return proto.CompactTextString(m) }
func (*OpenRsp) ProtoMessage()    {}
func (*OpenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{2}
}

func (m *OpenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRsp.Unmarshal(m, b)
}
func (m *OpenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRsp.Marshal(b, m, deterministic)
}
func (m *OpenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRsp.Merge(m, src)
}
func (m *OpenRsp) XXX_Size() int {
	return xxx_messageInfo_OpenRsp.Size(m)
}
func (m *OpenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRsp proto.InternalMessageInfo

func (m *OpenRsp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// Close data
type CloseRqst struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRqst) Reset()         { *m = CloseRqst{} }
func (m *CloseRqst) String() string { return proto.CompactTextString(m) }
func (*CloseRqst) ProtoMessage()    {}
func (*CloseRqst) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{3}
}

func (m *CloseRqst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRqst.Unmarshal(m, b)
}
func (m *CloseRqst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRqst.Marshal(b, m, deterministic)
}
func (m *CloseRqst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRqst.Merge(m, src)
}
func (m *CloseRqst) XXX_Size() int {
	return xxx_messageInfo_CloseRqst.Size(m)
}
func (m *CloseRqst) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRqst.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRqst proto.InternalMessageInfo

func (m *CloseRqst) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CloseRsp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRsp) Reset()         { *m = CloseRsp{} }
func (m *CloseRsp) String() string { return proto.CompactTextString(m) }
func (*CloseRsp) ProtoMessage()    {}
func (*CloseRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{4}
}

func (m *CloseRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRsp.Unmarshal(m, b)
}
func (m *CloseRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRsp.Marshal(b, m, deterministic)
}
func (m *CloseRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRsp.Merge(m, src)
}
func (m *CloseRsp) XXX_Size() int {
	return xxx_messageInfo_CloseRsp.Size(m)
}
func (m *CloseRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRsp proto.InternalMessageInfo

func (m *CloseRsp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// Create connection
type CreateConnectionRqst struct {
	Connection           *Connection `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateConnectionRqst) Reset()         { *m = CreateConnectionRqst{} }
func (m *CreateConnectionRqst) String() string { return proto.CompactTextString(m) }
func (*CreateConnectionRqst) ProtoMessage()    {}
func (*CreateConnectionRqst) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{5}
}

func (m *CreateConnectionRqst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConnectionRqst.Unmarshal(m, b)
}
func (m *CreateConnectionRqst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConnectionRqst.Marshal(b, m, deterministic)
}
func (m *CreateConnectionRqst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConnectionRqst.Merge(m, src)
}
func (m *CreateConnectionRqst) XXX_Size() int {
	return xxx_messageInfo_CreateConnectionRqst.Size(m)
}
func (m *CreateConnectionRqst) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConnectionRqst.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConnectionRqst proto.InternalMessageInfo

func (m *CreateConnectionRqst) GetConnection() *Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

type CreateConnectionRsp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConnectionRsp) Reset()         { *m = CreateConnectionRsp{} }
func (m *CreateConnectionRsp) String() string { return proto.CompactTextString(m) }
func (*CreateConnectionRsp) ProtoMessage()    {}
func (*CreateConnectionRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{6}
}

func (m *CreateConnectionRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConnectionRsp.Unmarshal(m, b)
}
func (m *CreateConnectionRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConnectionRsp.Marshal(b, m, deterministic)
}
func (m *CreateConnectionRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConnectionRsp.Merge(m, src)
}
func (m *CreateConnectionRsp) XXX_Size() int {
	return xxx_messageInfo_CreateConnectionRsp.Size(m)
}
func (m *CreateConnectionRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConnectionRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConnectionRsp proto.InternalMessageInfo

func (m *CreateConnectionRsp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// Delete connection
type DeleteConnectionRqst struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConnectionRqst) Reset()         { *m = DeleteConnectionRqst{} }
func (m *DeleteConnectionRqst) String() string { return proto.CompactTextString(m) }
func (*DeleteConnectionRqst) ProtoMessage()    {}
func (*DeleteConnectionRqst) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{7}
}

func (m *DeleteConnectionRqst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConnectionRqst.Unmarshal(m, b)
}
func (m *DeleteConnectionRqst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConnectionRqst.Marshal(b, m, deterministic)
}
func (m *DeleteConnectionRqst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConnectionRqst.Merge(m, src)
}
func (m *DeleteConnectionRqst) XXX_Size() int {
	return xxx_messageInfo_DeleteConnectionRqst.Size(m)
}
func (m *DeleteConnectionRqst) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConnectionRqst.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConnectionRqst proto.InternalMessageInfo

func (m *DeleteConnectionRqst) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteConnectionRsp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConnectionRsp) Reset()         { *m = DeleteConnectionRsp{} }
func (m *DeleteConnectionRsp) String() string { return proto.CompactTextString(m) }
func (*DeleteConnectionRsp) ProtoMessage()    {}
func (*DeleteConnectionRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{8}
}

func (m *DeleteConnectionRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConnectionRsp.Unmarshal(m, b)
}
func (m *DeleteConnectionRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConnectionRsp.Marshal(b, m, deterministic)
}
func (m *DeleteConnectionRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConnectionRsp.Merge(m, src)
}
func (m *DeleteConnectionRsp) XXX_Size() int {
	return xxx_messageInfo_DeleteConnectionRsp.Size(m)
}
func (m *DeleteConnectionRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConnectionRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConnectionRsp proto.InternalMessageInfo

func (m *DeleteConnectionRsp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// Save an item in the kv store
type SetItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetItemRequest) Reset()         { *m = SetItemRequest{} }
func (m *SetItemRequest) String() string { return proto.CompactTextString(m) }
func (*SetItemRequest) ProtoMessage()    {}
func (*SetItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{9}
}

func (m *SetItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetItemRequest.Unmarshal(m, b)
}
func (m *SetItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetItemRequest.Marshal(b, m, deterministic)
}
func (m *SetItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetItemRequest.Merge(m, src)
}
func (m *SetItemRequest) XXX_Size() int {
	return xxx_messageInfo_SetItemRequest.Size(m)
}
func (m *SetItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetItemRequest proto.InternalMessageInfo

func (m *SetItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetItemRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetItemRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetItemResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetItemResponse) Reset()         { *m = SetItemResponse{} }
func (m *SetItemResponse) String() string { return proto.CompactTextString(m) }
func (*SetItemResponse) ProtoMessage()    {}
func (*SetItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{10}
}

func (m *SetItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetItemResponse.Unmarshal(m, b)
}
func (m *SetItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetItemResponse.Marshal(b, m, deterministic)
}
func (m *SetItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetItemResponse.Merge(m, src)
}
func (m *SetItemResponse) XXX_Size() int {
	return xxx_messageInfo_SetItemResponse.Size(m)
}
func (m *SetItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetItemResponse proto.InternalMessageInfo

func (m *SetItemResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// Retreive a value with a given key
type GetItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemRequest) Reset()         { *m = GetItemRequest{} }
func (m *GetItemRequest) String() string { return proto.CompactTextString(m) }
func (*GetItemRequest) ProtoMessage()    {}
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{11}
}

func (m *GetItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemRequest.Unmarshal(m, b)
}
func (m *GetItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemRequest.Marshal(b, m, deterministic)
}
func (m *GetItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemRequest.Merge(m, src)
}
func (m *GetItemRequest) XXX_Size() int {
	return xxx_messageInfo_GetItemRequest.Size(m)
}
func (m *GetItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemRequest proto.InternalMessageInfo

func (m *GetItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetItemRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetItemResponse struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemResponse) Reset()         { *m = GetItemResponse{} }
func (m *GetItemResponse) String() string { return proto.CompactTextString(m) }
func (*GetItemResponse) ProtoMessage()    {}
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{12}
}

func (m *GetItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemResponse.Unmarshal(m, b)
}
func (m *GetItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemResponse.Marshal(b, m, deterministic)
}
func (m *GetItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemResponse.Merge(m, src)
}
func (m *GetItemResponse) XXX_Size() int {
	return xxx_messageInfo_GetItemResponse.Size(m)
}
func (m *GetItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemResponse proto.InternalMessageInfo

func (m *GetItemResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

// Remove an item from the store.
type RemoveItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveItemRequest) Reset()         { *m = RemoveItemRequest{} }
func (m *RemoveItemRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveItemRequest) ProtoMessage()    {}
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{13}
}

func (m *RemoveItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveItemRequest.Unmarshal(m, b)
}
func (m *RemoveItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveItemRequest.Marshal(b, m, deterministic)
}
func (m *RemoveItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveItemRequest.Merge(m, src)
}
func (m *RemoveItemRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveItemRequest.Size(m)
}
func (m *RemoveItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveItemRequest proto.InternalMessageInfo

func (m *RemoveItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RemoveItemRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RemoveItemResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveItemResponse) Reset()         { *m = RemoveItemResponse{} }
func (m *RemoveItemResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveItemResponse) ProtoMessage()    {}
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{14}
}

func (m *RemoveItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveItemResponse.Unmarshal(m, b)
}
func (m *RemoveItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveItemResponse.Marshal(b, m, deterministic)
}
func (m *RemoveItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveItemResponse.Merge(m, src)
}
func (m *RemoveItemResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveItemResponse.Size(m)
}
func (m *RemoveItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveItemResponse proto.InternalMessageInfo

func (m *RemoveItemResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// Remove all item from a stroe.
type ClearRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearRequest) Reset()         { *m = ClearRequest{} }
func (m *ClearRequest) String() string { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()    {}
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{15}
}

func (m *ClearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRequest.Unmarshal(m, b)
}
func (m *ClearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRequest.Marshal(b, m, deterministic)
}
func (m *ClearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRequest.Merge(m, src)
}
func (m *ClearRequest) XXX_Size() int {
	return xxx_messageInfo_ClearRequest.Size(m)
}
func (m *ClearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRequest proto.InternalMessageInfo

func (m *ClearRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ClearResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearResponse) Reset()         { *m = ClearResponse{} }
func (m *ClearResponse) String() string { return proto.CompactTextString(m) }
func (*ClearResponse) ProtoMessage()    {}
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{16}
}

func (m *ClearResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearResponse.Unmarshal(m, b)
}
func (m *ClearResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearResponse.Marshal(b, m, deterministic)
}
func (m *ClearResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearResponse.Merge(m, src)
}
func (m *ClearResponse) XXX_Size() int {
	return xxx_messageInfo_ClearResponse.Size(m)
}
func (m *ClearResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearResponse proto.InternalMessageInfo

func (m *ClearResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// Delte a data store
type DropRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropRequest) Reset()         { *m = DropRequest{} }
func (m *DropRequest) String() string { return proto.CompactTextString(m) }
func (*DropRequest) ProtoMessage()    {}
func (*DropRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{17}
}

func (m *DropRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropRequest.Unmarshal(m, b)
}
func (m *DropRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropRequest.Marshal(b, m, deterministic)
}
func (m *DropRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropRequest.Merge(m, src)
}
func (m *DropRequest) XXX_Size() int {
	return xxx_messageInfo_DropRequest.Size(m)
}
func (m *DropRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropRequest proto.InternalMessageInfo

func (m *DropRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DropResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DropResponse) Reset()         { *m = DropResponse{} }
func (m *DropResponse) String() string { return proto.CompactTextString(m) }
func (*DropResponse) ProtoMessage()    {}
func (*DropResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a67192205f4493, []int{18}
}

func (m *DropResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropResponse.Unmarshal(m, b)
}
func (m *DropResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropResponse.Marshal(b, m, deterministic)
}
func (m *DropResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropResponse.Merge(m, src)
}
func (m *DropResponse) XXX_Size() int {
	return xxx_messageInfo_DropResponse.Size(m)
}
func (m *DropResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DropResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DropResponse proto.InternalMessageInfo

func (m *DropResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterEnum("storage.StoreType", StoreType_name, StoreType_value)
	proto.RegisterType((*Connection)(nil), "storage.Connection")
	proto.RegisterType((*OpenRqst)(nil), "storage.OpenRqst")
	proto.RegisterType((*OpenRsp)(nil), "storage.OpenRsp")
	proto.RegisterType((*CloseRqst)(nil), "storage.CloseRqst")
	proto.RegisterType((*CloseRsp)(nil), "storage.CloseRsp")
	proto.RegisterType((*CreateConnectionRqst)(nil), "storage.CreateConnectionRqst")
	proto.RegisterType((*CreateConnectionRsp)(nil), "storage.CreateConnectionRsp")
	proto.RegisterType((*DeleteConnectionRqst)(nil), "storage.DeleteConnectionRqst")
	proto.RegisterType((*DeleteConnectionRsp)(nil), "storage.DeleteConnectionRsp")
	proto.RegisterType((*SetItemRequest)(nil), "storage.SetItemRequest")
	proto.RegisterType((*SetItemResponse)(nil), "storage.SetItemResponse")
	proto.RegisterType((*GetItemRequest)(nil), "storage.GetItemRequest")
	proto.RegisterType((*GetItemResponse)(nil), "storage.GetItemResponse")
	proto.RegisterType((*RemoveItemRequest)(nil), "storage.RemoveItemRequest")
	proto.RegisterType((*RemoveItemResponse)(nil), "storage.RemoveItemResponse")
	proto.RegisterType((*ClearRequest)(nil), "storage.ClearRequest")
	proto.RegisterType((*ClearResponse)(nil), "storage.ClearResponse")
	proto.RegisterType((*DropRequest)(nil), "storage.DropRequest")
	proto.RegisterType((*DropResponse)(nil), "storage.DropResponse")
}

func init() { proto.RegisterFile("storage/storagepb/storage.proto", fileDescriptor_22a67192205f4493) }

var fileDescriptor_22a67192205f4493 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0x51, 0x6f, 0xd2, 0x50,
	0x14, 0xc7, 0x81, 0xb1, 0x01, 0x07, 0x86, 0x70, 0x60, 0x93, 0x74, 0x4e, 0xe7, 0x7d, 0x40, 0x34,
	0x32, 0x0d, 0x73, 0x89, 0x4f, 0x26, 0x52, 0x48, 0xb7, 0xb8, 0xc4, 0x58, 0x8c, 0x31, 0xbe, 0x2c,
	0x1d, 0x3b, 0x31, 0x44, 0xe8, 0xed, 0xda, 0x42, 0xc2, 0xc7, 0xf4, 0x1b, 0x2d, 0xbd, 0x6d, 0x6f,
	0xbb, 0xb6, 0xb0, 0xec, 0x89, 0x7b, 0xcf, 0x39, 0xff, 0xdf, 0xc9, 0xbd, 0xf7, 0x7f, 0x28, 0xbc,
	0x72, 0x5c, 0x6e, 0x1b, 0x7f, 0xe9, 0x43, 0xf0, 0x6b, 0xdd, 0x84, 0xab, 0x53, 0xcb, 0xe6, 0x2e,
	0xc7, 0x52, 0xb0, 0x65, 0xbf, 0x01, 0x54, 0x6e, 0x9a, 0x34, 0x75, 0x67, 0xdc, 0xc4, 0x3a, 0x14,
	0x66, 0xb7, 0x9d, 0xfc, 0x49, 0xbe, 0x57, 0xd1, 0x0b, 0xb3, 0x5b, 0x44, 0x28, 0x9a, 0xc6, 0x82,
	0x3a, 0x05, 0x11, 0x11, 0x6b, 0xec, 0x42, 0xd1, 0x5d, 0x5b, 0xd4, 0xd9, 0x39, 0xc9, 0xf7, 0xea,
	0x03, 0x3c, 0x0d, 0xc1, 0x13, 0x97, 0xdb, 0xf4, 0x73, 0x6d, 0x91, 0x2e, 0xf2, 0xec, 0x13, 0x94,
	0xbf, 0x5b, 0x64, 0xea, 0x77, 0x8e, 0x9b, 0xe2, 0x76, 0xa0, 0xc4, 0x2d, 0xaf, 0xa3, 0x13, 0xa0,
	0xc3, 0x2d, 0x7b, 0x0d, 0x25, 0xa1, 0x72, 0x2c, 0x3c, 0x84, 0x3d, 0x9b, 0x9c, 0xe5, 0xdc, 0x15,
	0xc2, 0xb2, 0x1e, 0xec, 0xd8, 0x11, 0x54, 0xd4, 0x39, 0x77, 0x28, 0x8b, 0xcc, 0x18, 0x94, 0xfd,
	0xe4, 0x16, 0xc0, 0x37, 0x68, 0xab, 0x36, 0x19, 0x2e, 0x45, 0x27, 0x17, 0xac, 0x33, 0x80, 0xa9,
	0x8c, 0x08, 0x4d, 0x75, 0xd0, 0x92, 0xe7, 0x8b, 0x15, 0xc7, 0xca, 0x58, 0x1f, 0x5a, 0x29, 0xd8,
	0x96, 0xde, 0x5d, 0x68, 0x8f, 0x68, 0x4e, 0xa9, 0xde, 0xc9, 0x73, 0xf4, 0xa1, 0x95, 0xaa, 0xdb,
	0x82, 0xbd, 0x80, 0xfa, 0x84, 0xdc, 0x4b, 0x97, 0x16, 0x3a, 0xdd, 0x2d, 0x29, 0xe3, 0xca, 0x1b,
	0xb0, 0xf3, 0x8f, 0xd6, 0xc1, 0x75, 0x7b, 0x4b, 0x6c, 0xc3, 0xee, 0xca, 0x98, 0x2f, 0xfd, 0x97,
	0xac, 0xe9, 0xfe, 0x86, 0xbd, 0x85, 0x67, 0x92, 0xe4, 0x58, 0xdc, 0x74, 0x68, 0x63, 0xd3, 0x01,
	0xd4, 0xb5, 0x27, 0x36, 0xf5, 0xf0, 0xda, 0x56, 0x7c, 0x4d, 0xe2, 0xcf, 0xa1, 0xa9, 0xd3, 0x82,
	0xaf, 0xe8, 0x69, 0x1d, 0xde, 0x03, 0xc6, 0x65, 0x8f, 0x9c, 0xe1, 0x25, 0xd4, 0xd4, 0x39, 0x19,
	0xf6, 0x06, 0x3e, 0x7b, 0x03, 0xfb, 0x41, 0xfe, 0x11, 0xd0, 0x31, 0x54, 0x47, 0x36, 0xb7, 0x36,
	0x71, 0xba, 0x50, 0xf3, 0xd3, 0xdb, 0x31, 0xef, 0x7a, 0x50, 0x91, 0x83, 0x84, 0x35, 0x28, 0x5f,
	0x8d, 0x7f, 0x8d, 0xaf, 0xae, 0x47, 0xc3, 0x46, 0x0e, 0xf7, 0xa1, 0x32, 0xbc, 0xd4, 0xae, 0xd5,
	0xaf, 0xea, 0xc5, 0xb8, 0x91, 0x1f, 0xfc, 0x2f, 0x42, 0x7d, 0xe2, 0x7b, 0x73, 0x42, 0xf6, 0x6a,
	0x36, 0x25, 0xec, 0x43, 0xd1, 0x1b, 0x1e, 0x6c, 0x4a, 0xd3, 0x86, 0x13, 0xa8, 0x34, 0x1e, 0x86,
	0x1c, 0x8b, 0xe5, 0xf0, 0x23, 0xec, 0x8a, 0x59, 0xc1, 0x68, 0x88, 0xe5, 0x60, 0x29, 0xcd, 0x44,
	0x4c, 0x28, 0x7e, 0x40, 0x23, 0x69, 0x76, 0x3c, 0x8e, 0x0a, 0x33, 0x86, 0x4a, 0x79, 0xb1, 0x39,
	0x1d, 0x22, 0x93, 0x46, 0x8f, 0x21, 0xb3, 0x66, 0x25, 0x86, 0xcc, 0x18, 0x11, 0x96, 0xc3, 0x2f,
	0x50, 0x0a, 0x2c, 0x8c, 0xcf, 0xa3, 0xbf, 0xa7, 0x07, 0x4e, 0x55, 0x3a, 0xe9, 0x84, 0xff, 0x32,
	0xbe, 0x5e, 0x4b, 0xe9, 0xb5, 0x4d, 0x7a, 0x2d, 0xa5, 0xd7, 0x00, 0x22, 0x07, 0xa2, 0x22, 0x2b,
	0x53, 0x6e, 0x56, 0x8e, 0x32, 0x73, 0x12, 0xf4, 0xd9, 0x7b, 0x20, 0x32, 0x6c, 0x3c, 0x88, 0x3d,
	0x46, 0x64, 0x56, 0xe5, 0x30, 0x19, 0x96, 0xca, 0x73, 0x28, 0x7a, 0x76, 0xc3, 0x76, 0x74, 0x55,
	0x91, 0x39, 0x95, 0x83, 0x44, 0x34, 0x94, 0x0d, 0xab, 0x7f, 0x2a, 0xf2, 0x8b, 0x71, 0xb3, 0x27,
	0x3e, 0x15, 0x67, 0xf7, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x64, 0x79, 0xc5, 0x4d, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageServiceClient interface {
	// Open the store and set options...
	Open(ctx context.Context, in *OpenRqst, opts ...grpc.CallOption) (*OpenRsp, error)
	// Close the data store.
	Close(ctx context.Context, in *CloseRqst, opts ...grpc.CallOption) (*CloseRsp, error)
	// Create a connection.
	CreateConnection(ctx context.Context, in *CreateConnectionRqst, opts ...grpc.CallOption) (*CreateConnectionRsp, error)
	// Delete a connection.
	DeleteConnection(ctx context.Context, in *DeleteConnectionRqst, opts ...grpc.CallOption) (*DeleteConnectionRsp, error)
	// Save an item in the kv store
	SetItem(ctx context.Context, in *SetItemRequest, opts ...grpc.CallOption) (*SetItemResponse, error)
	// Retreive a value with a given key
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	// Remove an item with a given key
	RemoveItem(ctx context.Context, in *RemoveItemRequest, opts ...grpc.CallOption) (*RemoveItemResponse, error)
	// Remove all items
	Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
	// Drop a store
	Drop(ctx context.Context, in *DropRequest, opts ...grpc.CallOption) (*DropResponse, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) Open(ctx context.Context, in *OpenRqst, opts ...grpc.CallOption) (*OpenRsp, error) {
	out := new(OpenRsp)
	err := c.cc.Invoke(ctx, "/storage.StorageService/Open", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Close(ctx context.Context, in *CloseRqst, opts ...grpc.CallOption) (*CloseRsp, error) {
	out := new(CloseRsp)
	err := c.cc.Invoke(ctx, "/storage.StorageService/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreateConnection(ctx context.Context, in *CreateConnectionRqst, opts ...grpc.CallOption) (*CreateConnectionRsp, error) {
	out := new(CreateConnectionRsp)
	err := c.cc.Invoke(ctx, "/storage.StorageService/CreateConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteConnection(ctx context.Context, in *DeleteConnectionRqst, opts ...grpc.CallOption) (*DeleteConnectionRsp, error) {
	out := new(DeleteConnectionRsp)
	err := c.cc.Invoke(ctx, "/storage.StorageService/DeleteConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetItem(ctx context.Context, in *SetItemRequest, opts ...grpc.CallOption) (*SetItemResponse, error) {
	out := new(SetItemResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/SetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) RemoveItem(ctx context.Context, in *RemoveItemRequest, opts ...grpc.CallOption) (*RemoveItemResponse, error) {
	out := new(RemoveItemResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/RemoveItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/Clear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Drop(ctx context.Context, in *DropRequest, opts ...grpc.CallOption) (*DropResponse, error) {
	out := new(DropResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/Drop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
type StorageServiceServer interface {
	// Open the store and set options...
	Open(context.Context, *OpenRqst) (*OpenRsp, error)
	// Close the data store.
	Close(context.Context, *CloseRqst) (*CloseRsp, error)
	// Create a connection.
	CreateConnection(context.Context, *CreateConnectionRqst) (*CreateConnectionRsp, error)
	// Delete a connection.
	DeleteConnection(context.Context, *DeleteConnectionRqst) (*DeleteConnectionRsp, error)
	// Save an item in the kv store
	SetItem(context.Context, *SetItemRequest) (*SetItemResponse, error)
	// Retreive a value with a given key
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	// Remove an item with a given key
	RemoveItem(context.Context, *RemoveItemRequest) (*RemoveItemResponse, error)
	// Remove all items
	Clear(context.Context, *ClearRequest) (*ClearResponse, error)
	// Drop a store
	Drop(context.Context, *DropRequest) (*DropResponse, error)
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRqst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Open(ctx, req.(*OpenRqst))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRqst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Close(ctx, req.(*CloseRqst))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectionRqst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/CreateConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateConnection(ctx, req.(*CreateConnectionRqst))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConnectionRqst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/DeleteConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteConnection(ctx, req.(*DeleteConnectionRqst))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/SetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetItem(ctx, req.(*SetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_RemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).RemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/RemoveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).RemoveItem(ctx, req.(*RemoveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/Clear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Clear(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Drop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Drop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/Drop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Drop(ctx, req.(*DropRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _StorageService_Open_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _StorageService_Close_Handler,
		},
		{
			MethodName: "CreateConnection",
			Handler:    _StorageService_CreateConnection_Handler,
		},
		{
			MethodName: "DeleteConnection",
			Handler:    _StorageService_DeleteConnection_Handler,
		},
		{
			MethodName: "SetItem",
			Handler:    _StorageService_SetItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _StorageService_GetItem_Handler,
		},
		{
			MethodName: "RemoveItem",
			Handler:    _StorageService_RemoveItem_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _StorageService_Clear_Handler,
		},
		{
			MethodName: "Drop",
			Handler:    _StorageService_Drop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/storagepb/storage.proto",
}
