run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
issues:
  exclude-use-default: false
