#-- Docker install. --
FROM ubuntu
RUN apt-get update && apt-get install -y gnupg2 \
    wget \
  && rm -rf /var/lib/apt/lists/*
RUN wget https://s3-eu-west-1.amazonaws.com/deb.robustperception.io/41EFC99D.gpg && apt-key add 41EFC99D.gpg
RUN apt-get update && apt-get install -y \
  build-essential \
  curl \
  nano \
  python3 \
  python-is-python3 \
  mongodb

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow
RUN apt-get install -y ffmpeg

# -- Install prometheus
RUN wget https://github.com/prometheus/prometheus/releases/download/v2.23.0/prometheus-2.23.0.linux-armv7.tar.gz
RUN tar -xf prometheus-2.23.0.linux-armv7.tar.gz
RUN cp prometheus-2.23.0.linux-armv7/prometheus /usr/local/bin/
RUN cp prometheus-2.23.0.linux-armv7/promtool /usr/local/bin/
RUN cp -r prometheus-2.23.0.linux-armv7/consoles /etc/prometheus/
RUN cp -r prometheus-2.23.0.linux-armv7/console_libraries /etc/prometheus/
RUN rm -rf prometheus-2.23.0.linux-armv7*

# -- Install alert manager
RUN wget https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-armv7.tar.gz
RUN tar -xf alertmanager-0.21.0.linux-armv7.tar.gz
RUN cp alertmanager-0.21.0.linux-armv7/alertmanager /usr/local/bin
RUN rm -rf alertmanager-0.21.0.linux-armv7*

# -- Install node exporter
RUN wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-armv7.tar.gz
RUN tar -xf node_exporter-1.0.1.linux-armv7.tar.gz
RUN cp node_exporter-1.0.1.linux-armv7/node_exporter /usr/local/bin
RUN rm -rf node_exporter-1.0.1.linux-armv7*

# -- Install unix odbc drivers.
RUN curl http://www.unixodbc.org/unixODBC-2.3.7.tar.gz --output unixODBC-2.3.7.tar.gz
RUN tar -xvf unixODBC-2.3.7.tar.gz
RUN rm unixODBC-2.3.7.tar.gz
WORKDIR unixODBC-2.3.7
RUN ./configure && make all install clean && ldconfig

# -- Install zlib
RUN curl  https://zlib.net/zlib-1.2.11.tar.gz --output zlib-1.2.11.tar.gz
RUN tar -xvf zlib-1.2.11.tar.gz
RUN rm zlib-1.2.11.tar.gz
WORKDIR zlib-1.2.11
RUN ./configure && make all install clean && ldconfig

# -- Install xapian the search engine.
RUN curl  https://oligarchy.co.uk/xapian/1.4.18/xapian-core-1.4.18.tar.xz --output xapian-core-1.4.18.tar.xz
RUN tar -xvf xapian-core-1.4.18.tar.xz
RUN rm xapian-core-1.4.18.tar.xz
WORKDIR xapian-core-1.4.18
RUN ./configure && make all install clean && ldconfig

# -- Install youtube-dl
RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl --output /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl

# -- Copy globular files.
RUN mkdir /globular
ADD Globular /globular
COPY bin /globular/bin
COPY proto /globular/proto
COPY services /globular/services
COPY webroot /globular/webroot