#-- Docker install. --
FROM ubuntu

#-- install the basics
RUN apt-get update && apt-get install -y gnupg2 \
    wget \
  && rm -rf /var/lib/apt/lists/*

#-- needed by sql
RUN apt-get update && apt-get install -y \
  build-essential \
  && apt-get install -y \
  libltdl-dev 

#-- install ffmpeg
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow
RUN apt-get update && apt-get install -y ffmpeg && apt-get install wget

#-- install globular
RUN wget https://globule-dell.globular.cloud/mnt/data/distro/linux/globular_1.0.0-1.0.1_amd64.deb
RUN apt-get update && apt-get install -y ./globular_1.0.0-1.0.1_amd64.deb \
  && rm globular_1.0.0-1.0.1_amd64.deb

#-- stop the deamon...
RUN service Globular stop

# -- set the work dir
WORKDIR /usr/local/share/globular
ENV PATH="/usr/local/share/globular/bin:${PATH}"


# -- start globular exec.
ENTRYPOINT ["/usr/local/share/globular/Globular"]