/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.smtp.Email');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.smtp.CarbonCopy');

goog.forwardDeclare('proto.smtp.BodyType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.smtp.Email = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.smtp.Email.repeatedFields_, null);
};
goog.inherits(proto.smtp.Email, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.smtp.Email.displayName = 'proto.smtp.Email';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.smtp.Email.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.smtp.Email.prototype.toObject = function(opt_includeInstance) {
  return proto.smtp.Email.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.smtp.Email} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.smtp.Email.toObject = function(includeInstance, msg) {
  var f, obj = {
    from: jspb.Message.getFieldWithDefault(msg, 2, ""),
    toList: jspb.Message.getRepeatedField(msg, 3),
    ccList: jspb.Message.toObjectList(msg.getCcList(),
    proto.smtp.CarbonCopy.toObject, includeInstance),
    subject: jspb.Message.getFieldWithDefault(msg, 5, ""),
    body: jspb.Message.getFieldWithDefault(msg, 6, ""),
    bodytype: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.smtp.Email}
 */
proto.smtp.Email.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.smtp.Email;
  return proto.smtp.Email.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.smtp.Email} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.smtp.Email}
 */
proto.smtp.Email.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addTo(value);
      break;
    case 4:
      var value = new proto.smtp.CarbonCopy;
      reader.readMessage(value,proto.smtp.CarbonCopy.deserializeBinaryFromReader);
      msg.addCc(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 7:
      var value = /** @type {!proto.smtp.BodyType} */ (reader.readEnum());
      msg.setBodytype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.smtp.Email.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.smtp.Email.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.smtp.Email} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.smtp.Email.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getToList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getCcList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.smtp.CarbonCopy.serializeBinaryToWriter
    );
  }
  f = message.getSubject();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getBodytype();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional string from = 2;
 * @return {string}
 */
proto.smtp.Email.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.smtp.Email.prototype.setFrom = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string to = 3;
 * @return {!Array<string>}
 */
proto.smtp.Email.prototype.getToList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<string>} value */
proto.smtp.Email.prototype.setToList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.smtp.Email.prototype.addTo = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.smtp.Email.prototype.clearToList = function() {
  this.setToList([]);
};


/**
 * repeated CarbonCopy cc = 4;
 * @return {!Array<!proto.smtp.CarbonCopy>}
 */
proto.smtp.Email.prototype.getCcList = function() {
  return /** @type{!Array<!proto.smtp.CarbonCopy>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.smtp.CarbonCopy, 4));
};


/** @param {!Array<!proto.smtp.CarbonCopy>} value */
proto.smtp.Email.prototype.setCcList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.smtp.CarbonCopy=} opt_value
 * @param {number=} opt_index
 * @return {!proto.smtp.CarbonCopy}
 */
proto.smtp.Email.prototype.addCc = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.smtp.CarbonCopy, opt_index);
};


proto.smtp.Email.prototype.clearCcList = function() {
  this.setCcList([]);
};


/**
 * optional string subject = 5;
 * @return {string}
 */
proto.smtp.Email.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.smtp.Email.prototype.setSubject = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string body = 6;
 * @return {string}
 */
proto.smtp.Email.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.smtp.Email.prototype.setBody = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional BodyType bodyType = 7;
 * @return {!proto.smtp.BodyType}
 */
proto.smtp.Email.prototype.getBodytype = function() {
  return /** @type {!proto.smtp.BodyType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {!proto.smtp.BodyType} value */
proto.smtp.Email.prototype.setBodytype = function(value) {
  jspb.Message.setProto3EnumField(this, 7, value);
};


