package cluster

import (
	"encoding/base64"
	"fmt"
	"net"
	"net/http"
	"os"
)

// NewJoinScriptHandler serves a self-contained shell script that bootstraps
// a new node to join the cluster. The script follows a strict Day-1 protocol:
//
//	Phase 0: Preflight       — token, identity, targeted service stops
//	Phase 1: Directories     — create layout and globular user (no state wipe)
//	Phase 2: PKI/Identity    — CA cert, service cert, TLS verification
//	Phase 3: Connectivity    — DNS, /etc/hosts, libnss, journald, config.json, node-agent state
//	Phase 4: Download        — GitHub release tarball (same as Day-0): installer, packages, workflows
//	Phase 6: node-agent      — install and start; auto-initiates join RPC via state file
//	Phase 7: MinIO hold      — enforce objectstore topology contract
//
// The etcd cluster join (previously Phase 5) is now performed inside Phase 4.5
// by the globular-installer engine via the etcd_join spec step type. The step
// handles ghost cleanup, join-lock, member add, etcd.yaml, start, and membership
// verification — all in typed Go code with proper error handling.
//
// Repair mode (etcd WAL damage):
//
//	curl -sfL https://<gateway>:8443/join -k | sudo bash -s -- --token <TOKEN> --repair-etcd
//
// Usage (fresh Day-1 join):
//
//	curl -sfL https://<gateway>:8443/join -k | sudo bash -s -- --token <join-token>
func NewJoinScriptHandler(controllerAddr string, gatewayPort int, platformVersion string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}

		// Read CA certificate to embed in the script.
		caCert, err := os.ReadFile("/var/lib/globular/pki/ca.crt")
		if err != nil {
			http.Error(w, "CA certificate not found", http.StatusInternalServerError)
			return
		}
		caB64 := base64.StdEncoding.EncodeToString(caCert)

		// Determine the gateway address the client connected to.
		gatewayHost := r.Host
		if gatewayHost == "" {
			gatewayHost = r.URL.Host
		}

		reqHost, reqPort, err := net.SplitHostPort(gatewayHost)
		if err != nil {
			reqHost = gatewayHost
			reqPort = fmt.Sprintf("%d", gatewayPort)
		}
		if reqHost == "" || reqHost == "127.0.0.1" || reqHost == "::1" || reqHost == "localhost" {
			// Never embed a loopback address — the joining node is remote.
			if h, _, splitErr := net.SplitHostPort(r.RemoteAddr); splitErr == nil {
				reqHost = h
			}
		}

		gatewayAddr := net.JoinHostPort(reqHost, reqPort)

		ctrlAddr := controllerAddr
		ctrlHost, _, _ := net.SplitHostPort(ctrlAddr)
		if ctrlAddr == "" || ctrlHost == "127.0.0.1" || ctrlHost == "localhost" || ctrlHost == "::1" {
			ctrlAddr = fmt.Sprintf("%s:12000", reqHost)
		}

		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		fmt.Fprintf(w, joinScript, caB64, gatewayAddr, ctrlAddr, platformVersion)
	})
}

// joinScript is the shell script template served to joining nodes.
// Format args (all positional to avoid ambiguity with shell ${} syntax):
//
//	%[1]s = base64 CA cert
//	%[2]s = gateway address (host:port)
//	%[3]s = controller address (host:port)
//	%[4]s = platform version (e.g. "1.2.88") — used to build the GitHub release tarball URL
//
// IMPORTANT: any literal %% in this string becomes % in the output script.
// Use %% wherever the shell script needs a literal % (e.g. date format strings).
const joinScript = `#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Globular Day-1 Node Join Script
# Generated by the bootstrap gateway — do not edit manually.
#
# Phases:
#   0 — Preflight:   token required, identity detection, targeted service stops
#   1 — Directories: create layout, globular user (no state wipe)
#   2 — PKI/Identity: CA cert, service cert, TLS smoke-test
#   3 — Connectivity: DNS, /etc/hosts MinIO fallback, libnss, journald
#   3.6 — JoinPlan: POST /join/authorize → signed JoinPlan + join_id from controller
#   3.7 — Seeds:    write etcd_endpoints file so ScyllaDB post-install finds seeds
#   3.8 — State:    write node-agent state.json including join_id
#   4 — Download:   GitHub release tarball → globular-installer, packages, workflows
#   5 — Etcd join:  ghost cleanup, member add, etcd.yaml, start, health gate, fork-detection
#   6 — node-agent: write unit (After=globular-etcd), start; uses v2 path (join_id)
#   7 — MinIO hold: enforce objectstore topology contract
#
# Phase 3.6 is the JoinPlan authorization gate. The gateway is a courier only —
# the controller assigns profiles, etcd intent, node_id, and signs the plan.
# No cluster-affecting step (Phase 4+) runs before Phase 3.6 succeeds.
#
# The node-agent reads join_token + controller_endpoint + join_id from state
# and auto-initiates the v2 join path on startup (no RequestJoin call needed).
# After the join is approved the controller drives all further convergence:
#   admitted → infra_preparing → etcd_ready → xds_ready →
#   envoy_ready → storage_joining → workload_ready
#
# Repair mode (etcd WAL corrupt or permanently removed from cluster):
#   ... | sudo bash -s -- --token <TOKEN> --repair-etcd
#   This mode REQUIRES explicit operator intent. It backs up and wipes
#   /var/lib/globular/etcd before rejoining. Never wiped without this flag.
# ============================================================================

# ── Embedded cluster parameters ─────────────────────────────────────────────
CA_B64="%[1]s"
GATEWAY="%[2]s"
CONTROLLER="%[3]s"

# ── Runtime defaults ─────────────────────────────────────────────────────────
JOIN_TOKEN=""
REPAIR_ETCD=0
INSTALL_DIR="/usr/lib/globular/bin"
STATE_DIR="/var/lib/globular"
SYSTEMD_DIR="/etc/systemd/system"

# ── Argument parsing ─────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --token)       JOIN_TOKEN="$2"; shift 2 ;;
    --controller)  CONTROLLER="$2"; shift 2 ;;
    --repair-etcd) REPAIR_ETCD=1; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

[[ -n "${JOIN_TOKEN}" ]] || {
  echo "Error: --token is required" >&2
  echo "Usage: curl -sfL https://<gateway>:8443/join -k | sudo bash -s -- --token <TOKEN>" >&2
  exit 1
}

# ── Helpers ──────────────────────────────────────────────────────────────────
die()       { echo "  FAIL: $*" >&2; exit 1; }
log_ok()    { echo "  OK:   $*"; }
log_info()  { echo "  ...   $*"; }
log_warn()  { echo "  WARN: $*" >&2; }
log_phase() { echo ""; echo "══════════════════════════════════════════════════════"; echo "PHASE $*"; echo "══════════════════════════════════════════════════════"; echo ""; }

[[ "$(id -u)" -eq 0 ]] || die "This script must be run as root (sudo)"

BOOTSTRAP_HOST=$(echo "${GATEWAY}" | cut -d: -f1)
BOOTSTRAP_ETCD="https://${BOOTSTRAP_HOST}:2379"
NODE_HOSTNAME=$(hostname)
NODE_IP=$(hostname -I | awk '{print $1}')
ETCD_NAME="${NODE_HOSTNAME}"
PKI_DIR="${STATE_DIR}/pki/issued/services"
ETCD_CACERT="${STATE_DIR}/pki/ca.crt"
ETCD_CERT="${PKI_DIR}/service.crt"
ETCD_KEY="${PKI_DIR}/service.key"

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║          GLOBULAR DAY-1 NODE JOIN                               ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  Controller: ${CONTROLLER}"
echo "  Gateway:    ${GATEWAY}"
echo "  Bootstrap:  ${BOOTSTRAP_HOST}"
echo "  This node:  ${NODE_HOSTNAME} (${NODE_IP})"
if [[ ${REPAIR_ETCD} -eq 1 ]]; then
  echo "  Mode:       REPAIR-ETCD (WAL backup + wipe authorized)"
else
  echo "  Mode:       fresh Day-1 join"
fi
echo ""

# ============================================================================
log_phase "0 — Preflight"
# ============================================================================
# Stop ONLY the services that must be reset for this join sequence.
# Do not wildcard-stop all globular-* services.

log_info "[0.1] Stopping globular-etcd and globular-node-agent if running..."
for unit in globular-etcd.service globular-node-agent.service; do
  if systemctl is-active --quiet "${unit}" 2>/dev/null; then
    log_info "Stopping ${unit}..."
    systemctl stop "${unit}" 2>/dev/null || true
  fi
done

# Repair mode: back up etcd WAL then wipe — ONLY with explicit --repair-etcd.
# Without this flag the script FAILS if etcd data exists, forcing an
# explicit operator decision rather than silently destroying cluster state.
if [[ ${REPAIR_ETCD} -eq 1 ]]; then
  log_info "[0.2] Repair mode: backing up etcd data before wipe..."
  if [[ -d "${STATE_DIR}/etcd" ]]; then
    ETCD_BACKUP="${STATE_DIR}/etcd.bak.$(date +%%Y%%m%%dT%%H%%M%%S)"
    cp -a "${STATE_DIR}/etcd" "${ETCD_BACKUP}" \
      || die "etcd backup to ${ETCD_BACKUP} failed — refusing to wipe without a successful backup"
    log_ok "etcd backup written: ${ETCD_BACKUP}"
    rm -rf "${STATE_DIR}/etcd"
    log_ok "etcd data dir wiped (backup at ${ETCD_BACKUP})"
  else
    log_info "no etcd data dir found — nothing to wipe"
  fi
elif [[ -d "${STATE_DIR}/etcd" ]] && [[ -n "$(ls -A "${STATE_DIR}/etcd" 2>/dev/null)" ]]; then
  die "etcd data directory exists at ${STATE_DIR}/etcd and --repair-etcd was not given.
  If this node had a failed or broken etcd join, use --repair-etcd to
  authorize a WAL backup and wipe. Never wipe without explicit operator intent."
fi

log_ok "Preflight complete"

# ============================================================================
log_phase "1 — Directories and globular user"
# ============================================================================
# Create directory layout and the globular system user.
# No etcd.yaml, no PKI material, no node identity is written here.
# State wipe already handled in Phase 0 (repair only) or by clean-node.sh.

log_info "[1.1] Creating directories..."
mkdir -p "${INSTALL_DIR}" \
         "${STATE_DIR}/pki/issued/services" \
         "${STATE_DIR}/services" \
         "${STATE_DIR}/node_agent" \
         "${STATE_DIR}/config" \
         "${STATE_DIR}/workflows" \
         "${STATE_DIR}/keys"

if ! id -u globular &>/dev/null; then
  useradd --system --no-create-home --home-dir "${STATE_DIR}" --shell /usr/sbin/nologin globular
fi
log_ok "Directories and user ready"

# ============================================================================
log_phase "2 — PKI / Identity"
# ============================================================================

log_info "[2.1] Installing cluster CA certificate..."
echo "${CA_B64}" | base64 -d > "${STATE_DIR}/pki/ca.crt"
cp "${STATE_DIR}/pki/ca.crt" "${STATE_DIR}/pki/ca.pem"
chmod 644 "${STATE_DIR}/pki/ca.crt" "${STATE_DIR}/pki/ca.pem"

# Install into system trust store so curl and Go TLS work with the cluster CA.
cp "${STATE_DIR}/pki/ca.crt" /usr/local/share/ca-certificates/globular-ca.crt
update-ca-certificates >/dev/null 2>&1 || true
log_ok "CA certificate installed and trusted"

log_info "[2.2] Generating service certificate..."
openssl genrsa -out "${PKI_DIR}/service.key" 2048 2>/dev/null

cat > /tmp/globular-san.cnf <<SANEOF
[req]
req_extensions     = v3_req
distinguished_name = req_dn
prompt             = no
[req_dn]
CN = ${NODE_HOSTNAME}
O  = globular.internal
[v3_req]
subjectAltName = DNS:${NODE_HOSTNAME},DNS:${NODE_HOSTNAME}.globular.internal,DNS:localhost,IP:${NODE_IP},IP:127.0.0.1
SANEOF

openssl req -new -key "${PKI_DIR}/service.key" \
  -config /tmp/globular-san.cnf \
  -out /tmp/globular-join.csr 2>/dev/null

CSR_B64=$(base64 -w0 /tmp/globular-join.csr)
curl -sfL --cacert "${STATE_DIR}/pki/ca.crt" \
  "https://${GATEWAY}/sign_ca_certificate?csr=${CSR_B64}" \
  -o "${PKI_DIR}/service.crt"
rm -f /tmp/globular-join.csr /tmp/globular-san.cnf

[[ -s "${PKI_DIR}/service.crt" ]] \
  || die "Certificate signing failed — controller returned empty certificate"

chmod 600 "${PKI_DIR}/service.key"
chmod 644 "${PKI_DIR}/service.crt"
log_ok "Service certificate issued for ${NODE_HOSTNAME} (${NODE_IP})"

log_info "[2.3] Verifying TLS access to bootstrap gateway..."
if curl -sf --cacert "${STATE_DIR}/pki/ca.crt" -o /dev/null \
  "https://${GATEWAY}/get_ca_certificate" 2>/dev/null; then
  log_ok "Bootstrap gateway reachable via TLS"
else
  log_warn "Gateway TLS check failed — DNS may not be set yet; continuing"
fi

# ============================================================================
log_phase "3 — Connectivity"
# ============================================================================

log_info "[3.1] Configuring DNS resolver (*.globular.internal → bootstrap)..."
mkdir -p /etc/systemd/resolved.conf.d
cat > /etc/systemd/resolved.conf.d/globular.conf <<DNSCONF
[Resolve]
DNS=${BOOTSTRAP_HOST}
Domains=~globular.internal
DNSCONF
systemctl restart systemd-resolved 2>/dev/null || true
log_ok "DNS resolver → ${BOOTSTRAP_HOST} for globular.internal"

# -- MinIO /etc/hosts fallback (objectstore topology contract) ---------------
#
# This node is NOT automatically a MinIO/objectstore member on Day-1.
# Objectstore membership is governed solely by ObjectStoreDesiredState in
# etcd, written by the controller after explicit 'globular objectstore
# apply-topology'. No topology mutation happens here.
#
# The bootstrap node is written as the ONLY /etc/hosts MinIO entry so that
# artifact fetches resolve before DNS propagates. This node's own IP is
# never written as a MinIO endpoint by the join script.
log_info "[3.2] Adding MinIO /etc/hosts fallback (bootstrap objectstore only)..."
sed -i '/minio\.globular\.internal/d' /etc/hosts
echo "${BOOTSTRAP_HOST} minio.globular.internal  # MinIO bootstrap fallback — ObjectStoreDesiredState governs topology" >> /etc/hosts
log_ok "minio.globular.internal → ${BOOTSTRAP_HOST} (bootstrap; topology contract governs membership)"

log_info "[3.3] Ensuring libnss-resolve (systemd-resolved bridge for Go binaries)..."
if ! dpkg -l libnss-resolve 2>/dev/null | grep -q '^ii'; then
  apt-get install -y libnss-resolve >/dev/null 2>&1 || true
fi
if grep -q 'mdns4_minimal.*NOTFOUND.*return' /etc/nsswitch.conf; then
  sed -i 's/^hosts:.*/hosts:          files resolve dns myhostname/' /etc/nsswitch.conf
fi
log_ok "libnss-resolve configured"

log_info "[3.4] Configuring log rate limits (prevent syslog/journal disk fill)..."
mkdir -p /etc/rsyslog.d
cat > /etc/rsyslog.d/50-globular-rate-limit.conf <<'RSYSLOG'
$SystemLogRateLimitInterval 10
$SystemLogRateLimitBurst 500
RSYSLOG
systemctl restart rsyslog 2>/dev/null || true

mkdir -p /etc/systemd/journald.conf.d
cat > /etc/systemd/journald.conf.d/50-globular.conf <<'JOURNALD'
[Journal]
SystemMaxUse=2G
SystemKeepFree=10G
MaxRetentionSec=7day
JOURNALD
systemctl restart systemd-journald 2>/dev/null || true
log_ok "rsyslog rate-limited, journald capped at 2GB/7days"

log_info "[3.5] Writing node-agent seed config.json..."
cat > "${STATE_DIR}/config.json" <<CFGJSON
{
  "Address": "${NODE_IP}",
  "AlternateDomains": [],
  "Domain": "globular.internal",
  "EnablePeerUpserts": false,
  "EtcdClientPort": "2379",
  "EtcdConfigPath": "${STATE_DIR}/config/etcd.yaml",
  "EtcdDataDir": "${STATE_DIR}/etcd",
  "EtcdEnabled": true,
  "EtcdMode": "existing",
  "EtcdName": "${NODE_HOSTNAME}",
  "EtcdPeerPort": "2380",
  "MutateHostsFile": false,
  "MutateResolvConf": false,
  "Name": "${NODE_HOSTNAME}",
  "Peers": [],
  "PortHTTP": 8080,
  "PortHTTPS": 8443,
  "Protocol": "https",
  "Services": {}
}
CFGJSON

chown -R globular:globular "${STATE_DIR}"
chown globular:globular "${STATE_DIR}/keys"

log_info "[3.6] Obtaining signed JoinPlan from controller (v2 authorization gate)..."
# ────────────────────────────────────────────────────────────────────────────
# Phase A.1: The gateway is a courier. The controller is the authority.
# This call must succeed before any cluster-affecting step (Phase 4+).
# Cluster-affecting steps: etcd member add, writing cluster membership config,
# starting node-agent as a joined node, applying assigned profiles.
# ────────────────────────────────────────────────────────────────────────────
mkdir -p "${STATE_DIR}/nodeagent"

AUTHORIZE_RESPONSE="${STATE_DIR}/nodeagent/join_authorize.json"

# Build the authorization request JSON (no bash arrays; use printf for safety)
AUTHORIZE_BODY=$(printf '{"join_token":"%%s","identity":{"hostname":"%%s","ips":["%%s"]}}' \
  "${JOIN_TOKEN}" "${NODE_HOSTNAME}" "${NODE_IP}")

# Use -w to capture HTTP status separately; do NOT use -f so the response body
# is always written to AUTHORIZE_RESPONSE regardless of HTTP status code.
# This lets us extract denied_reason from a 403 instead of hiding it.
AUTHORIZE_HTTP_STATUS=$(curl -sL --cacert "${STATE_DIR}/pki/ca.crt" \
  -X POST "https://${GATEWAY}/join/authorize" \
  -H "Content-Type: application/json" \
  -d "${AUTHORIZE_BODY}" \
  -o "${AUTHORIZE_RESPONSE}" \
  -w "%%{http_code}" 2>/dev/null) \
  || die "join blocked: network error reaching gateway /join/authorize"

if [[ "${AUTHORIZE_HTTP_STATUS}" -ge 500 ]]; then
  GATEWAY_ERR=$(head -1 "${AUTHORIZE_RESPONSE}" 2>/dev/null || true)
  die "join blocked: gateway error (HTTP ${AUTHORIZE_HTTP_STATUS}) — ${GATEWAY_ERR}"
fi

# Parse allowed field: handles both "allowed":true and "allowed": true
JOIN_PLAN_ALLOWED=$(grep -oE '"allowed"\s*:\s*(true|false)' "${AUTHORIZE_RESPONSE}" \
  | head -1 | grep -oE '(true|false)$' || echo "false")

# Extract join_id and denied_reason from response JSON
JOIN_ID=$(grep -oE '"join_id"\s*:\s*"[^"]*"' "${AUTHORIZE_RESPONSE}" \
  | head -1 | sed 's/.*"join_id"\s*:\s*"\([^"]*\)".*/\1/' || echo "")

DENIED_REASON=$(grep -oE '"denied_reason"\s*:\s*"[^"]*"' "${AUTHORIZE_RESPONSE}" \
  | head -1 | sed 's/.*"denied_reason"\s*:\s*"\([^"]*\)".*/\1/' || echo "unknown")

[[ "${JOIN_PLAN_ALLOWED}" == "true" ]] \
  || die "join blocked: controller denied — ${DENIED_REASON}"

[[ -n "${JOIN_ID}" ]] \
  || die "join blocked: signed JoinPlan missing — controller returned empty join_id"

log_ok "join plan accepted: join_id=${JOIN_ID} generation=controller-authorized"

log_info "[3.7] Writing etcd endpoints file (seed for ScyllaDB post-install)..."
# ScyllaDB's post-install reads this file to discover seed nodes.
# Without it the file is absent and ScyllaDB falls back to the local IP only,
# bootstrapping a standalone cluster instead of joining the existing ring.
# The node-agent's recovery path only writes this file after 3 heartbeat
# failures, which is too late — it must exist before storage_joining triggers.
echo "https://${BOOTSTRAP_HOST}:2379" > "${STATE_DIR}/config/etcd_endpoints"
chown globular:globular "${STATE_DIR}/config/etcd_endpoints"
log_ok "etcd_endpoints seeded with bootstrap host (${BOOTSTRAP_HOST})"

log_info "[3.8] Writing node-agent state (join token + controller endpoint + join_id)..."
# The join_id is included so the node-agent uses the v2 path (no RequestJoin call):
# it polls GetJoinRequestStatus(join_id) directly without consuming the token again.
cat > "${STATE_DIR}/nodeagent/state.json" <<STATEJSON
{
  "controller_endpoint": "${CONTROLLER}",
  "controller_insecure": false,
  "request_id": "",
  "node_id": "",
  "join_token": "${JOIN_TOKEN}",
  "join_id": "${JOIN_ID}",
  "network_generation": 0,
  "cluster_domain": "globular.internal",
  "protocol": "https"
}
STATEJSON
chown -R globular:globular "${STATE_DIR}/nodeagent"
log_ok "node-agent state seeded (join_token set, join_id=${JOIN_ID}, controller=${CONTROLLER})"

log_ok "Connectivity configured"

# ============================================================================
log_phase "4 — Download Release Tarball from GitHub"
# ============================================================================
# Use the same release tarball as Day-0. It contains globular-installer,
# all packages, and all workflow definitions — no gateway package serving needed.

PLATFORM_VERSION="%[4]s"

if [[ -z "${PLATFORM_VERSION}" || "${PLATFORM_VERSION}" == "0.0.0-dev" || "${PLATFORM_VERSION}" == "0.0.0-detect" ]]; then
  die "cannot download release tarball: no valid platform version (version=${PLATFORM_VERSION})"
fi

TARBALL_NAME="globular-${PLATFORM_VERSION}-linux-amd64.tar.gz"
TARBALL_URL="https://github.com/globulario/services/releases/download/v${PLATFORM_VERSION}/${TARBALL_NAME}"
TARBALL_TMP="/tmp/${TARBALL_NAME}"
TARBALL_DIR="/tmp/globular-${PLATFORM_VERSION}"

log_info "[4.1] Downloading ${TARBALL_NAME} from GitHub..."
curl -sfL "${TARBALL_URL}" -o "${TARBALL_TMP}" \
  || die "could not download ${TARBALL_NAME} from GitHub v${PLATFORM_VERSION}"
curl -sfL "${TARBALL_URL}.sha256" -o "${TARBALL_TMP}.sha256" \
  || die "could not download checksum for ${TARBALL_NAME}"

EXPECTED_SUM=$(awk '{print $1}' "${TARBALL_TMP}.sha256")
ACTUAL_SUM=$(sha256sum "${TARBALL_TMP}" | awk '{print $1}')
if [[ "${EXPECTED_SUM}" != "${ACTUAL_SUM}" ]]; then
  die "tarball checksum mismatch (expected ${EXPECTED_SUM}, got ${ACTUAL_SUM})"
fi
rm -f "${TARBALL_TMP}.sha256"
log_ok "tarball verified (sha256 ok)"

log_info "[4.2] Extracting tarball..."
mkdir -p "${TARBALL_DIR}"
tar -xzf "${TARBALL_TMP}" -C "${TARBALL_DIR}" --strip-components=1
rm -f "${TARBALL_TMP}"
log_ok "tarball extracted"

[[ -x "${TARBALL_DIR}/globular-installer" ]] || die "globular-installer not found in tarball"
[[ -d "${TARBALL_DIR}/packages" ]]           || die "packages/ not found in tarball"

cp "${TARBALL_DIR}/globular-installer" "${INSTALL_DIR}/globular-installer"
chmod +x "${INSTALL_DIR}/globular-installer"

log_info "[4.3] Staging packages to ${STATE_DIR}/packages/ ..."
# Move all packages to their canonical location so the node-agent can install
# them locally during convergence without re-fetching from the repository service.
mkdir -p "${STATE_DIR}/packages"
mv "${TARBALL_DIR}/packages/"* "${STATE_DIR}/packages/"
chown -R globular:globular "${STATE_DIR}/packages"
PACKAGES_DIR="${STATE_DIR}/packages"

log_info "[4.4] Copying workflows to state dir..."
cp -r "${TARBALL_DIR}/workflows/." "${STATE_DIR}/workflows/"
chown -R globular:globular "${STATE_DIR}/workflows"
log_ok "globular-installer, packages, and workflows ready"

log_info "[4.5] Installing etcdctl (required by etcd cluster join step)..."
ETCDCTL_PKG=$(find "${PACKAGES_DIR}" -maxdepth 1 -name "etcdctl_*_linux_amd64.tgz" 2>/dev/null | head -1)
if [[ -n "${ETCDCTL_PKG}" ]]; then
  "${INSTALL_DIR}/globular-installer" install \
    --non-interactive \
    "${ETCDCTL_PKG}" \
    || log_warn "etcdctl install failed (non-fatal, will retry via etcd package)"
  ln -sf "${INSTALL_DIR}/etcdctl" /usr/local/bin/etcdctl
  log_ok "etcdctl installed"
else
  log_warn "etcdctl package not found — etcd join may fail if etcdctl is unavailable"
fi

log_info "[4.6] Installing etcd binary and service unit (cluster join in Phase 5)..."
# join_id=${JOIN_ID} — Phase 3.6 validated the JoinPlan. Cluster-affecting steps start in Phase 5.
ETCD_PKG=$(find "${PACKAGES_DIR}" -maxdepth 1 -name "etcd_*_linux_amd64.tgz" 2>/dev/null | head -1)
if [[ -z "${ETCD_PKG}" ]]; then
  die "etcd package not found in ${PACKAGES_DIR} — Phase 4.2 download may have failed"
fi
mkdir -p "${STATE_DIR}/etcd"
chown -R globular:globular "${STATE_DIR}/config" "${STATE_DIR}/etcd"
"${INSTALL_DIR}/globular-installer" install \
  --non-interactive --verbose \
  "${ETCD_PKG}" \
  || die "installer: etcd binary installation failed"
ln -sf "${INSTALL_DIR}/etcdctl" /usr/local/bin/etcdctl
log_ok "etcd binary and service unit installed"

# The installer may have started etcd immediately with a default single-node
# bootstrap config (initial-cluster-state=new). Stop it and wipe any data it
# created so Phase 5 can write the proper join config and start clean.
log_info "[4.6.1] Stopping installer-started etcd and wiping transient bootstrap data..."
systemctl stop globular-etcd.service 2>/dev/null || true
rm -rf "${STATE_DIR}/etcd"
mkdir -p "${STATE_DIR}/etcd"
chown globular:globular "${STATE_DIR}/etcd"
log_ok "installer-started etcd stopped; data dir reset for cluster join"

# ============================================================================
log_phase "5 — Etcd Cluster Join"
# ============================================================================
# All cluster-affecting etcd operations are explicit and auditable here.
# Phase 3.6 (JoinPlan) already authorized this join. join_id=${JOIN_ID}

log_info "[5.1] Checking for ghost etcd member (peer URL from prior failed join)..."
GHOST_ID=$(etcdctl \
  --endpoints="${BOOTSTRAP_ETCD}" \
  --cacert="${ETCD_CACERT}" --cert="${ETCD_CERT}" --key="${ETCD_KEY}" \
  member list 2>/dev/null \
  | awk -F', ' -v peer="https://${NODE_IP}:2380" '$4==peer {print $1}' | head -1 || true)
if [[ -n "${GHOST_ID}" ]]; then
  log_warn "ghost member detected (peer URL match): ${GHOST_ID} — removing before member add"
  etcdctl \
    --endpoints="${BOOTSTRAP_ETCD}" \
    --cacert="${ETCD_CACERT}" --cert="${ETCD_CERT}" --key="${ETCD_KEY}" \
    member remove "${GHOST_ID}" \
    || log_warn "ghost removal failed — member add may still succeed if peer URL was released"
  log_ok "ghost member removed"
fi

log_info "[5.2] Fetching current cluster member list from ${BOOTSTRAP_ETCD}..."
INITIAL_CLUSTER_RAW=$(etcdctl \
  --endpoints="${BOOTSTRAP_ETCD}" \
  --cacert="${ETCD_CACERT}" --cert="${ETCD_CERT}" --key="${ETCD_KEY}" \
  member list 2>/dev/null \
  | awk -F', ' 'NF>=4 && $3!="" {print $3"="$4}' | paste -sd, || true)

log_info "[5.3] Normalizing loopback peer URLs (bootstrap may have 127.0.0.1)..."
INITIAL_CLUSTER="${INITIAL_CLUSTER_RAW//127.0.0.1/${BOOTSTRAP_HOST}}"
log_ok "initial-cluster: ${INITIAL_CLUSTER}"

log_info "[5.4] Writing etcd.yaml (initial-cluster-state: existing)..."
mkdir -p "${STATE_DIR}/config"
cat > "${STATE_DIR}/config/etcd.yaml" <<ETCDCFG
name: ${ETCD_NAME}
data-dir: ${STATE_DIR}/etcd

initial-advertise-peer-urls: https://${NODE_IP}:2380
listen-peer-urls: https://0.0.0.0:2380
advertise-client-urls: https://${NODE_IP}:2379
listen-client-urls: https://0.0.0.0:2379

initial-cluster: ${INITIAL_CLUSTER},${ETCD_NAME}=https://${NODE_IP}:2380
initial-cluster-state: "existing"

client-transport-security:
  cert-file: ${ETCD_CERT}
  key-file: ${ETCD_KEY}
  trusted-ca-file: ${ETCD_CACERT}
  client-cert-auth: true

peer-transport-security:
  cert-file: ${ETCD_CERT}
  key-file: ${ETCD_KEY}
  trusted-ca-file: ${ETCD_CACERT}
  client-cert-auth: true
ETCDCFG
chown globular:globular "${STATE_DIR}/config/etcd.yaml"
chmod 640 "${STATE_DIR}/config/etcd.yaml"
log_ok "etcd.yaml written (initial-cluster-state=existing, no loopback peer URLs)"

log_info "[5.5] Adding ${ETCD_NAME} to cluster via etcdctl member add..."
etcdctl \
  --endpoints="${BOOTSTRAP_ETCD}" \
  --cacert="${ETCD_CACERT}" --cert="${ETCD_CERT}" --key="${ETCD_KEY}" \
  member add "${ETCD_NAME}" \
  --peer-urls="https://${NODE_IP}:2380" \
  || die "etcd join failed: member add rejected by bootstrap cluster"
log_ok "member add accepted: ${ETCD_NAME}"

log_info "[5.6] Starting globular-etcd.service..."
systemctl daemon-reload
systemctl enable globular-etcd.service 2>/dev/null || true
systemctl start globular-etcd.service \
  || die "etcd join failed: systemctl start globular-etcd.service returned non-zero"

log_info "[5.6.1] Waiting for local etcd to become healthy (max 60s)..."
ETCD_OK=0
for i in $(seq 1 60); do
  if etcdctl \
    --endpoints="https://${NODE_IP}:2379" \
    --cacert="${ETCD_CACERT}" --cert="${ETCD_CERT}" --key="${ETCD_KEY}" \
    endpoint health >/dev/null 2>&1; then
    ETCD_OK=1
    break
  fi
  sleep 1
done
if [[ ${ETCD_OK} -ne 1 ]]; then
  die "etcd did not become healthy after 60s — etcd join failed; check: journalctl -u globular-etcd"
fi
log_ok "etcd healthy on ${NODE_IP}:2379"

log_info "[5.7] Verifying named member presence in cluster (anti-fork check)..."
# Query BOOTSTRAP_ETCD — not local NODE_IP. A forked standalone etcd passes a local check;
# only the bootstrap view proves the node actually joined the existing cluster.
VISIBLE=$(etcdctl \
  --endpoints="${BOOTSTRAP_ETCD}" \
  --cacert="${ETCD_CACERT}" --cert="${ETCD_CERT}" --key="${ETCD_KEY}" \
  member list 2>/dev/null | awk -F', ' 'NF>=4 {print $3}' \
  | grep -c "^${ETCD_NAME}$" || echo 0)
if [[ "${VISIBLE}" -eq 0 ]]; then
  die "etcd join failed: ${ETCD_NAME} is not visible in cluster member list from ${BOOTSTRAP_ETCD} — \
this node may have forked its own cluster instead of joining the existing one; \
wipe etcd data and retry with --repair-etcd"
fi
log_ok "member ${ETCD_NAME} confirmed visible in cluster (anti-fork verified)"

# ============================================================================
log_phase "6 — node-agent"
# ============================================================================
# Install the node-agent binary, write a systemd unit that declares an
# ordering dependency on globular-etcd.service, then start it.
# The node-agent reads join_token + controller_endpoint + join_id from the
# state file written in Phase 3.8 and uses the v2 path at startup:
# it polls GetJoinRequestStatus(join_id) without calling RequestJoin again.

log_info "[6.1] Installing globular-node-agent binary via installer engine (join_id=${JOIN_ID})..."
NODE_AGENT_PKG=$(find "${PACKAGES_DIR}" -maxdepth 1 \( -name "node-agent_*_linux_amd64.tgz" -o -name "node_agent_*_linux_amd64.tgz" \) 2>/dev/null | head -1)
if [[ -z "${NODE_AGENT_PKG}" ]]; then
  die "node-agent package not found in ${PACKAGES_DIR} — Phase 4.2 download may have failed"
fi
"${INSTALL_DIR}/globular-installer" install \
  --non-interactive --verbose \
  "${NODE_AGENT_PKG}" \
  || die "installer: node-agent install failed"

log_info "[6.2] Writing node-agent systemd unit (After=globular-etcd.service)..."
NODE_AGENT_BIN=$(find "${INSTALL_DIR}" -maxdepth 1 \( -name "node_agent_server" -o -name "globular-node-agent" \) 2>/dev/null | head -1 || echo "${INSTALL_DIR}/node_agent_server")
cat > "${SYSTEMD_DIR}/globular-node-agent.service" <<NAUNIT
[Unit]
Description=Globular Node Agent
After=network-online.target globular-etcd.service
Requires=network-online.target
Requires=globular-etcd.service

[Service]
User=globular
ExecStart=${NODE_AGENT_BIN} ${STATE_DIR}
Restart=on-failure
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
NAUNIT
systemctl daemon-reload
systemctl enable globular-node-agent.service 2>/dev/null || true
log_ok "node-agent unit written (Requires=globular-etcd.service)"

log_info "[6.3] Starting globular-node-agent.service..."
systemctl start globular-node-agent.service \
  || log_warn "node-agent start returned non-zero — controller will retry join RPC"

log_info "[6.4] Waiting for node-agent to listen on :11000..."
AGENT_UP=0
for i in $(seq 1 30); do
  if ss -tlnp 2>/dev/null | grep -q ":11000 "; then
    AGENT_UP=1
    break
  fi
  sleep 1
done
if [[ ${AGENT_UP} -ne 1 ]]; then
  log_warn "node-agent not yet listening on :11000 — controller will retry join RPC"
fi
log_ok "node-agent running"

# ============================================================================
log_phase "6.5 — Cleanup installation tarball"
# ============================================================================
log_info "[6.5] Removing extracted tarball (no longer needed)..."
rm -rf "${TARBALL_DIR}"
log_ok "Tarball cleaned up"

# ============================================================================
log_phase "7 — MinIO / Objectstore Hold Enforcement"
# ============================================================================
# The join script MUST NOT start globular-minio.service.
# Objectstore topology is exclusively governed by ObjectStoreDesiredState in
# etcd via 'globular objectstore apply-topology'.
# The controller and node-agent start MinIO ONLY when this node is admitted
# as an objectstore member by an approved TopologyTransition.

log_info "[7.1] Enforcing MinIO hold (objectstore topology contract)..."
if systemctl is-active --quiet globular-minio.service 2>/dev/null; then
  log_warn "globular-minio.service is active — stopping (topology contract violation)"
  systemctl stop globular-minio.service 2>/dev/null || true
fi
if systemctl is-enabled --quiet globular-minio.service 2>/dev/null; then
  systemctl disable globular-minio.service 2>/dev/null || true
  log_info "globular-minio.service disabled (controller drives objectstore topology)"
fi
log_ok "MinIO held — controller owns objectstore topology"

# ============================================================================
echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║          NODE JOINED SUCCESSFULLY                               ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  Identity:     ${NODE_HOSTNAME} (${NODE_IP})"
echo "  etcd:         healthy, member '${ETCD_NAME}'"
echo "  node-agent:   running, auto-initiating join RPC"
echo "  MinIO:        held (not a topology member)"
echo ""
echo "  The node-agent is submitting the join request to the controller."
echo "  Once approved, the controller drives bootstrap convergence:"
echo "    admitted → infra_preparing → etcd_ready →"
echo "    xds_ready → envoy_ready → storage_joining → workload_ready"
echo ""
echo "  Monitor from any cluster node: globular cluster nodes list"
echo ""
`
