// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin/admin.proto

package admin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//* more can be append here *
type Platform int32

const (
	Platform_LINUX32 Platform = 0
	Platform_LINUX64 Platform = 1
	Platform_WIN32   Platform = 2
	Platform_WIN64   Platform = 3
)

var Platform_name = map[int32]string{
	0: "LINUX32",
	1: "LINUX64",
	2: "WIN32",
	3: "WIN64",
}

var Platform_value = map[string]int32{
	"LINUX32": 0,
	"LINUX64": 1,
	"WIN32":   2,
	"WIN64":   3,
}

func (x Platform) String() string {
	return proto.EnumName(Platform_name, int32(x))
}

func (Platform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{0}
}

// Return the configuration of the whole server.
type GetConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{0}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

type GetConfigResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{1}
}

func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(m, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type SaveConfigRequest struct {
	Config               string   `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveConfigRequest) Reset()         { *m = SaveConfigRequest{} }
func (m *SaveConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SaveConfigRequest) ProtoMessage()    {}
func (*SaveConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{2}
}

func (m *SaveConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveConfigRequest.Unmarshal(m, b)
}
func (m *SaveConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveConfigRequest.Marshal(b, m, deterministic)
}
func (m *SaveConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveConfigRequest.Merge(m, src)
}
func (m *SaveConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SaveConfigRequest.Size(m)
}
func (m *SaveConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveConfigRequest proto.InternalMessageInfo

func (m *SaveConfigRequest) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type SaveConfigResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveConfigResponse) Reset()         { *m = SaveConfigResponse{} }
func (m *SaveConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SaveConfigResponse) ProtoMessage()    {}
func (*SaveConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{3}
}

func (m *SaveConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveConfigResponse.Unmarshal(m, b)
}
func (m *SaveConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveConfigResponse.Marshal(b, m, deterministic)
}
func (m *SaveConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveConfigResponse.Merge(m, src)
}
func (m *SaveConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SaveConfigResponse.Size(m)
}
func (m *SaveConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveConfigResponse proto.InternalMessageInfo

func (m *SaveConfigResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type StopServiceRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServiceRequest) Reset()         { *m = StopServiceRequest{} }
func (m *StopServiceRequest) String() string { return proto.CompactTextString(m) }
func (*StopServiceRequest) ProtoMessage()    {}
func (*StopServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{4}
}

func (m *StopServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServiceRequest.Unmarshal(m, b)
}
func (m *StopServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServiceRequest.Marshal(b, m, deterministic)
}
func (m *StopServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServiceRequest.Merge(m, src)
}
func (m *StopServiceRequest) XXX_Size() int {
	return xxx_messageInfo_StopServiceRequest.Size(m)
}
func (m *StopServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopServiceRequest proto.InternalMessageInfo

func (m *StopServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type StopServiceResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServiceResponse) Reset()         { *m = StopServiceResponse{} }
func (m *StopServiceResponse) String() string { return proto.CompactTextString(m) }
func (*StopServiceResponse) ProtoMessage()    {}
func (*StopServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{5}
}

func (m *StopServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServiceResponse.Unmarshal(m, b)
}
func (m *StopServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServiceResponse.Marshal(b, m, deterministic)
}
func (m *StopServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServiceResponse.Merge(m, src)
}
func (m *StopServiceResponse) XXX_Size() int {
	return xxx_messageInfo_StopServiceResponse.Size(m)
}
func (m *StopServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopServiceResponse proto.InternalMessageInfo

func (m *StopServiceResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type StartServiceRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartServiceRequest) Reset()         { *m = StartServiceRequest{} }
func (m *StartServiceRequest) String() string { return proto.CompactTextString(m) }
func (*StartServiceRequest) ProtoMessage()    {}
func (*StartServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{6}
}

func (m *StartServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartServiceRequest.Unmarshal(m, b)
}
func (m *StartServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartServiceRequest.Marshal(b, m, deterministic)
}
func (m *StartServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartServiceRequest.Merge(m, src)
}
func (m *StartServiceRequest) XXX_Size() int {
	return xxx_messageInfo_StartServiceRequest.Size(m)
}
func (m *StartServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartServiceRequest proto.InternalMessageInfo

func (m *StartServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

// Return the pid of
type StartServiceResponse struct {
	ServicePid           int64    `protobuf:"varint,1,opt,name=service_pid,json=servicePid,proto3" json:"service_pid,omitempty"`
	ProxyPid             int64    `protobuf:"varint,2,opt,name=proxy_pid,json=proxyPid,proto3" json:"proxy_pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartServiceResponse) Reset()         { *m = StartServiceResponse{} }
func (m *StartServiceResponse) String() string { return proto.CompactTextString(m) }
func (*StartServiceResponse) ProtoMessage()    {}
func (*StartServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{7}
}

func (m *StartServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartServiceResponse.Unmarshal(m, b)
}
func (m *StartServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartServiceResponse.Marshal(b, m, deterministic)
}
func (m *StartServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartServiceResponse.Merge(m, src)
}
func (m *StartServiceResponse) XXX_Size() int {
	return xxx_messageInfo_StartServiceResponse.Size(m)
}
func (m *StartServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartServiceResponse proto.InternalMessageInfo

func (m *StartServiceResponse) GetServicePid() int64 {
	if m != nil {
		return m.ServicePid
	}
	return 0
}

func (m *StartServiceResponse) GetProxyPid() int64 {
	if m != nil {
		return m.ProxyPid
	}
	return 0
}

// Register an external service.
type RegisterExternalApplicationRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Args                 []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterExternalApplicationRequest) Reset()         { *m = RegisterExternalApplicationRequest{} }
func (m *RegisterExternalApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterExternalApplicationRequest) ProtoMessage()    {}
func (*RegisterExternalApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{8}
}

func (m *RegisterExternalApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterExternalApplicationRequest.Unmarshal(m, b)
}
func (m *RegisterExternalApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterExternalApplicationRequest.Marshal(b, m, deterministic)
}
func (m *RegisterExternalApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterExternalApplicationRequest.Merge(m, src)
}
func (m *RegisterExternalApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterExternalApplicationRequest.Size(m)
}
func (m *RegisterExternalApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterExternalApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterExternalApplicationRequest proto.InternalMessageInfo

func (m *RegisterExternalApplicationRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *RegisterExternalApplicationRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RegisterExternalApplicationRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

// Return the pid of the service.
type RegisterExternalApplicationResponse struct {
	ServicePid           int64    `protobuf:"varint,1,opt,name=service_pid,json=servicePid,proto3" json:"service_pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterExternalApplicationResponse) Reset()         { *m = RegisterExternalApplicationResponse{} }
func (m *RegisterExternalApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterExternalApplicationResponse) ProtoMessage()    {}
func (*RegisterExternalApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{9}
}

func (m *RegisterExternalApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterExternalApplicationResponse.Unmarshal(m, b)
}
func (m *RegisterExternalApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterExternalApplicationResponse.Marshal(b, m, deterministic)
}
func (m *RegisterExternalApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterExternalApplicationResponse.Merge(m, src)
}
func (m *RegisterExternalApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterExternalApplicationResponse.Size(m)
}
func (m *RegisterExternalApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterExternalApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterExternalApplicationResponse proto.InternalMessageInfo

func (m *RegisterExternalApplicationResponse) GetServicePid() int64 {
	if m != nil {
		return m.ServicePid
	}
	return 0
}

type SetRootPasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRootPasswordRequest) Reset()         { *m = SetRootPasswordRequest{} }
func (m *SetRootPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetRootPasswordRequest) ProtoMessage()    {}
func (*SetRootPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{10}
}

func (m *SetRootPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRootPasswordRequest.Unmarshal(m, b)
}
func (m *SetRootPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRootPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetRootPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRootPasswordRequest.Merge(m, src)
}
func (m *SetRootPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetRootPasswordRequest.Size(m)
}
func (m *SetRootPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRootPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRootPasswordRequest proto.InternalMessageInfo

func (m *SetRootPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *SetRootPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type SetRootPasswordResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRootPasswordResponse) Reset()         { *m = SetRootPasswordResponse{} }
func (m *SetRootPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetRootPasswordResponse) ProtoMessage()    {}
func (*SetRootPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{11}
}

func (m *SetRootPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRootPasswordResponse.Unmarshal(m, b)
}
func (m *SetRootPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRootPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetRootPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRootPasswordResponse.Merge(m, src)
}
func (m *SetRootPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetRootPasswordResponse.Size(m)
}
func (m *SetRootPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRootPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetRootPasswordResponse proto.InternalMessageInfo

func (m *SetRootPasswordResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SetRootEmailRequest struct {
	OldEmail             string   `protobuf:"bytes,1,opt,name=oldEmail,proto3" json:"oldEmail,omitempty"`
	NewEmail             string   `protobuf:"bytes,2,opt,name=newEmail,proto3" json:"newEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRootEmailRequest) Reset()         { *m = SetRootEmailRequest{} }
func (m *SetRootEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SetRootEmailRequest) ProtoMessage()    {}
func (*SetRootEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{12}
}

func (m *SetRootEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRootEmailRequest.Unmarshal(m, b)
}
func (m *SetRootEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRootEmailRequest.Marshal(b, m, deterministic)
}
func (m *SetRootEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRootEmailRequest.Merge(m, src)
}
func (m *SetRootEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SetRootEmailRequest.Size(m)
}
func (m *SetRootEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRootEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRootEmailRequest proto.InternalMessageInfo

func (m *SetRootEmailRequest) GetOldEmail() string {
	if m != nil {
		return m.OldEmail
	}
	return ""
}

func (m *SetRootEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type SetRootEmailResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRootEmailResponse) Reset()         { *m = SetRootEmailResponse{} }
func (m *SetRootEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SetRootEmailResponse) ProtoMessage()    {}
func (*SetRootEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{13}
}

func (m *SetRootEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRootEmailResponse.Unmarshal(m, b)
}
func (m *SetRootEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRootEmailResponse.Marshal(b, m, deterministic)
}
func (m *SetRootEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRootEmailResponse.Merge(m, src)
}
func (m *SetRootEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SetRootEmailResponse.Size(m)
}
func (m *SetRootEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRootEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetRootEmailResponse proto.InternalMessageInfo

func (m *SetRootEmailResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SetPasswordRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordRequest) Reset()         { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()    {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{14}
}

func (m *SetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordRequest.Unmarshal(m, b)
}
func (m *SetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordRequest.Merge(m, src)
}
func (m *SetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetPasswordRequest.Size(m)
}
func (m *SetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordRequest proto.InternalMessageInfo

func (m *SetPasswordRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SetPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *SetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type SetPasswordResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordResponse) Reset()         { *m = SetPasswordResponse{} }
func (m *SetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetPasswordResponse) ProtoMessage()    {}
func (*SetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{15}
}

func (m *SetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordResponse.Unmarshal(m, b)
}
func (m *SetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordResponse.Merge(m, src)
}
func (m *SetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetPasswordResponse.Size(m)
}
func (m *SetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordResponse proto.InternalMessageInfo

func (m *SetPasswordResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SetEmailRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	OldEmail             string   `protobuf:"bytes,2,opt,name=oldEmail,proto3" json:"oldEmail,omitempty"`
	NewEmail             string   `protobuf:"bytes,3,opt,name=newEmail,proto3" json:"newEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetEmailRequest) Reset()         { *m = SetEmailRequest{} }
func (m *SetEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SetEmailRequest) ProtoMessage()    {}
func (*SetEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{16}
}

func (m *SetEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetEmailRequest.Unmarshal(m, b)
}
func (m *SetEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetEmailRequest.Marshal(b, m, deterministic)
}
func (m *SetEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetEmailRequest.Merge(m, src)
}
func (m *SetEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SetEmailRequest.Size(m)
}
func (m *SetEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetEmailRequest proto.InternalMessageInfo

func (m *SetEmailRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *SetEmailRequest) GetOldEmail() string {
	if m != nil {
		return m.OldEmail
	}
	return ""
}

func (m *SetEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type SetEmailResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetEmailResponse) Reset()         { *m = SetEmailResponse{} }
func (m *SetEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SetEmailResponse) ProtoMessage()    {}
func (*SetEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{17}
}

func (m *SetEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetEmailResponse.Unmarshal(m, b)
}
func (m *SetEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetEmailResponse.Marshal(b, m, deterministic)
}
func (m *SetEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetEmailResponse.Merge(m, src)
}
func (m *SetEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SetEmailResponse.Size(m)
}
func (m *SetEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetEmailResponse proto.InternalMessageInfo

func (m *SetEmailResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PublishServiceRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	PublisherId          string   `protobuf:"bytes,2,opt,name=publisherId,proto3" json:"publisherId,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	DicorveryId          string   `protobuf:"bytes,4,opt,name=dicorveryId,proto3" json:"dicorveryId,omitempty"`
	RepositoryId         string   `protobuf:"bytes,5,opt,name=repositoryId,proto3" json:"repositoryId,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Keywords             []string `protobuf:"bytes,7,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Version              string   `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	Platform             Platform `protobuf:"varint,9,opt,name=platform,proto3,enum=admin.Platform" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishServiceRequest) Reset()         { *m = PublishServiceRequest{} }
func (m *PublishServiceRequest) String() string { return proto.CompactTextString(m) }
func (*PublishServiceRequest) ProtoMessage()    {}
func (*PublishServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{18}
}

func (m *PublishServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishServiceRequest.Unmarshal(m, b)
}
func (m *PublishServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishServiceRequest.Marshal(b, m, deterministic)
}
func (m *PublishServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishServiceRequest.Merge(m, src)
}
func (m *PublishServiceRequest) XXX_Size() int {
	return xxx_messageInfo_PublishServiceRequest.Size(m)
}
func (m *PublishServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishServiceRequest proto.InternalMessageInfo

func (m *PublishServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *PublishServiceRequest) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

func (m *PublishServiceRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PublishServiceRequest) GetDicorveryId() string {
	if m != nil {
		return m.DicorveryId
	}
	return ""
}

func (m *PublishServiceRequest) GetRepositoryId() string {
	if m != nil {
		return m.RepositoryId
	}
	return ""
}

func (m *PublishServiceRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PublishServiceRequest) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *PublishServiceRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PublishServiceRequest) GetPlatform() Platform {
	if m != nil {
		return m.Platform
	}
	return Platform_LINUX32
}

type UploadServicePackageRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadServicePackageRequest) Reset()         { *m = UploadServicePackageRequest{} }
func (m *UploadServicePackageRequest) String() string { return proto.CompactTextString(m) }
func (*UploadServicePackageRequest) ProtoMessage()    {}
func (*UploadServicePackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{19}
}

func (m *UploadServicePackageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadServicePackageRequest.Unmarshal(m, b)
}
func (m *UploadServicePackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadServicePackageRequest.Marshal(b, m, deterministic)
}
func (m *UploadServicePackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadServicePackageRequest.Merge(m, src)
}
func (m *UploadServicePackageRequest) XXX_Size() int {
	return xxx_messageInfo_UploadServicePackageRequest.Size(m)
}
func (m *UploadServicePackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadServicePackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadServicePackageRequest proto.InternalMessageInfo

func (m *UploadServicePackageRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadServicePackageResponse struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadServicePackageResponse) Reset()         { *m = UploadServicePackageResponse{} }
func (m *UploadServicePackageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadServicePackageResponse) ProtoMessage()    {}
func (*UploadServicePackageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{20}
}

func (m *UploadServicePackageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadServicePackageResponse.Unmarshal(m, b)
}
func (m *UploadServicePackageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadServicePackageResponse.Marshal(b, m, deterministic)
}
func (m *UploadServicePackageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadServicePackageResponse.Merge(m, src)
}
func (m *UploadServicePackageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadServicePackageResponse.Size(m)
}
func (m *UploadServicePackageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadServicePackageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadServicePackageResponse proto.InternalMessageInfo

func (m *UploadServicePackageResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type PublishServiceResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishServiceResponse) Reset()         { *m = PublishServiceResponse{} }
func (m *PublishServiceResponse) String() string { return proto.CompactTextString(m) }
func (*PublishServiceResponse) ProtoMessage()    {}
func (*PublishServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{21}
}

func (m *PublishServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishServiceResponse.Unmarshal(m, b)
}
func (m *PublishServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishServiceResponse.Marshal(b, m, deterministic)
}
func (m *PublishServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishServiceResponse.Merge(m, src)
}
func (m *PublishServiceResponse) XXX_Size() int {
	return xxx_messageInfo_PublishServiceResponse.Size(m)
}
func (m *PublishServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishServiceResponse proto.InternalMessageInfo

func (m *PublishServiceResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type InstallServiceRequest struct {
	DicorveryId          string   `protobuf:"bytes,1,opt,name=dicorveryId,proto3" json:"dicorveryId,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	PublisherId          string   `protobuf:"bytes,3,opt,name=publisherId,proto3" json:"publisherId,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallServiceRequest) Reset()         { *m = InstallServiceRequest{} }
func (m *InstallServiceRequest) String() string { return proto.CompactTextString(m) }
func (*InstallServiceRequest) ProtoMessage()    {}
func (*InstallServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{22}
}

func (m *InstallServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallServiceRequest.Unmarshal(m, b)
}
func (m *InstallServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallServiceRequest.Marshal(b, m, deterministic)
}
func (m *InstallServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallServiceRequest.Merge(m, src)
}
func (m *InstallServiceRequest) XXX_Size() int {
	return xxx_messageInfo_InstallServiceRequest.Size(m)
}
func (m *InstallServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallServiceRequest proto.InternalMessageInfo

func (m *InstallServiceRequest) GetDicorveryId() string {
	if m != nil {
		return m.DicorveryId
	}
	return ""
}

func (m *InstallServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *InstallServiceRequest) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

func (m *InstallServiceRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type InstallServiceResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallServiceResponse) Reset()         { *m = InstallServiceResponse{} }
func (m *InstallServiceResponse) String() string { return proto.CompactTextString(m) }
func (*InstallServiceResponse) ProtoMessage()    {}
func (*InstallServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{23}
}

func (m *InstallServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallServiceResponse.Unmarshal(m, b)
}
func (m *InstallServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallServiceResponse.Marshal(b, m, deterministic)
}
func (m *InstallServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallServiceResponse.Merge(m, src)
}
func (m *InstallServiceResponse) XXX_Size() int {
	return xxx_messageInfo_InstallServiceResponse.Size(m)
}
func (m *InstallServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstallServiceResponse proto.InternalMessageInfo

func (m *InstallServiceResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type UninstallServiceRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	PublisherId          string   `protobuf:"bytes,2,opt,name=publisherId,proto3" json:"publisherId,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UninstallServiceRequest) Reset()         { *m = UninstallServiceRequest{} }
func (m *UninstallServiceRequest) String() string { return proto.CompactTextString(m) }
func (*UninstallServiceRequest) ProtoMessage()    {}
func (*UninstallServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{24}
}

func (m *UninstallServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UninstallServiceRequest.Unmarshal(m, b)
}
func (m *UninstallServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UninstallServiceRequest.Marshal(b, m, deterministic)
}
func (m *UninstallServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UninstallServiceRequest.Merge(m, src)
}
func (m *UninstallServiceRequest) XXX_Size() int {
	return xxx_messageInfo_UninstallServiceRequest.Size(m)
}
func (m *UninstallServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UninstallServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UninstallServiceRequest proto.InternalMessageInfo

func (m *UninstallServiceRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *UninstallServiceRequest) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

func (m *UninstallServiceRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type UninstallServiceResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UninstallServiceResponse) Reset()         { *m = UninstallServiceResponse{} }
func (m *UninstallServiceResponse) String() string { return proto.CompactTextString(m) }
func (*UninstallServiceResponse) ProtoMessage()    {}
func (*UninstallServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{25}
}

func (m *UninstallServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UninstallServiceResponse.Unmarshal(m, b)
}
func (m *UninstallServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UninstallServiceResponse.Marshal(b, m, deterministic)
}
func (m *UninstallServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UninstallServiceResponse.Merge(m, src)
}
func (m *UninstallServiceResponse) XXX_Size() int {
	return xxx_messageInfo_UninstallServiceResponse.Size(m)
}
func (m *UninstallServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UninstallServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UninstallServiceResponse proto.InternalMessageInfo

func (m *UninstallServiceResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type DeployApplicationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployApplicationRequest) Reset()         { *m = DeployApplicationRequest{} }
func (m *DeployApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationRequest) ProtoMessage()    {}
func (*DeployApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{26}
}

func (m *DeployApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationRequest.Unmarshal(m, b)
}
func (m *DeployApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationRequest.Marshal(b, m, deterministic)
}
func (m *DeployApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationRequest.Merge(m, src)
}
func (m *DeployApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationRequest.Size(m)
}
func (m *DeployApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationRequest proto.InternalMessageInfo

func (m *DeployApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployApplicationRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeployApplicationResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployApplicationResponse) Reset()         { *m = DeployApplicationResponse{} }
func (m *DeployApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationResponse) ProtoMessage()    {}
func (*DeployApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8595c8dce2486799, []int{27}
}

func (m *DeployApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationResponse.Unmarshal(m, b)
}
func (m *DeployApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationResponse.Marshal(b, m, deterministic)
}
func (m *DeployApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationResponse.Merge(m, src)
}
func (m *DeployApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationResponse.Size(m)
}
func (m *DeployApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationResponse proto.InternalMessageInfo

func (m *DeployApplicationResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterEnum("admin.Platform", Platform_name, Platform_value)
	proto.RegisterType((*GetConfigRequest)(nil), "admin.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "admin.GetConfigResponse")
	proto.RegisterType((*SaveConfigRequest)(nil), "admin.SaveConfigRequest")
	proto.RegisterType((*SaveConfigResponse)(nil), "admin.SaveConfigResponse")
	proto.RegisterType((*StopServiceRequest)(nil), "admin.StopServiceRequest")
	proto.RegisterType((*StopServiceResponse)(nil), "admin.StopServiceResponse")
	proto.RegisterType((*StartServiceRequest)(nil), "admin.StartServiceRequest")
	proto.RegisterType((*StartServiceResponse)(nil), "admin.StartServiceResponse")
	proto.RegisterType((*RegisterExternalApplicationRequest)(nil), "admin.RegisterExternalApplicationRequest")
	proto.RegisterType((*RegisterExternalApplicationResponse)(nil), "admin.RegisterExternalApplicationResponse")
	proto.RegisterType((*SetRootPasswordRequest)(nil), "admin.SetRootPasswordRequest")
	proto.RegisterType((*SetRootPasswordResponse)(nil), "admin.SetRootPasswordResponse")
	proto.RegisterType((*SetRootEmailRequest)(nil), "admin.SetRootEmailRequest")
	proto.RegisterType((*SetRootEmailResponse)(nil), "admin.SetRootEmailResponse")
	proto.RegisterType((*SetPasswordRequest)(nil), "admin.SetPasswordRequest")
	proto.RegisterType((*SetPasswordResponse)(nil), "admin.SetPasswordResponse")
	proto.RegisterType((*SetEmailRequest)(nil), "admin.SetEmailRequest")
	proto.RegisterType((*SetEmailResponse)(nil), "admin.SetEmailResponse")
	proto.RegisterType((*PublishServiceRequest)(nil), "admin.PublishServiceRequest")
	proto.RegisterType((*UploadServicePackageRequest)(nil), "admin.UploadServicePackageRequest")
	proto.RegisterType((*UploadServicePackageResponse)(nil), "admin.UploadServicePackageResponse")
	proto.RegisterType((*PublishServiceResponse)(nil), "admin.PublishServiceResponse")
	proto.RegisterType((*InstallServiceRequest)(nil), "admin.InstallServiceRequest")
	proto.RegisterType((*InstallServiceResponse)(nil), "admin.InstallServiceResponse")
	proto.RegisterType((*UninstallServiceRequest)(nil), "admin.UninstallServiceRequest")
	proto.RegisterType((*UninstallServiceResponse)(nil), "admin.UninstallServiceResponse")
	proto.RegisterType((*DeployApplicationRequest)(nil), "admin.DeployApplicationRequest")
	proto.RegisterType((*DeployApplicationResponse)(nil), "admin.DeployApplicationResponse")
}

func init() { proto.RegisterFile("admin/admin.proto", fileDescriptor_8595c8dce2486799) }

var fileDescriptor_8595c8dce2486799 = []byte{
	// 1005 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x9e, 0x2d, 0x27, 0xb1, 0x8e, 0xb3, 0xd4, 0x61, 0xd3, 0x44, 0x51, 0x92, 0xd5, 0x50, 0x6f,
	0xb2, 0xa6, 0x6b, 0x37, 0x3b, 0xe8, 0xc5, 0x06, 0x0c, 0x48, 0xd6, 0x36, 0x30, 0xb0, 0x14, 0x86,
	0xbd, 0x60, 0xc5, 0x30, 0x60, 0x60, 0x2d, 0xd6, 0x15, 0xa2, 0x88, 0x9a, 0x44, 0x3b, 0xcd, 0x73,
	0xec, 0x25, 0xf6, 0x04, 0x7b, 0xbe, 0x41, 0x14, 0x49, 0x51, 0x3f, 0x96, 0xb3, 0xf5, 0xc6, 0x20,
	0xcf, 0x3f, 0xbf, 0x43, 0x7e, 0x3a, 0x86, 0x6d, 0xec, 0xde, 0x78, 0xc1, 0x0b, 0xfe, 0xfb, 0x3c,
	0x8c, 0x28, 0xa3, 0x68, 0x8d, 0x6f, 0x1c, 0x04, 0xdd, 0x0b, 0xc2, 0x7e, 0xa2, 0xc1, 0x07, 0x6f,
	0x36, 0x26, 0x7f, 0xce, 0x49, 0xcc, 0x9c, 0x13, 0xd8, 0xd6, 0x64, 0x71, 0x48, 0x83, 0x98, 0xa0,
	0x5d, 0x58, 0x8f, 0x48, 0x3c, 0xf7, 0x99, 0xd5, 0xe8, 0x35, 0x8e, 0xcd, 0xb1, 0xd8, 0x25, 0xc6,
	0x13, 0xbc, 0x20, 0xb9, 0x08, 0x89, 0xf1, 0x94, 0x0b, 0xa4, 0x71, 0xba, 0x73, 0x9e, 0x01, 0xd2,
	0x8d, 0x57, 0x84, 0x1e, 0x00, 0x9a, 0x30, 0x1a, 0x4e, 0x48, 0xb4, 0xf0, 0xa6, 0x44, 0xc6, 0x3e,
	0x02, 0x88, 0x53, 0xc9, 0x1f, 0x9e, 0x2b, 0x3c, 0x4c, 0x21, 0x19, 0xba, 0xce, 0x37, 0xf0, 0x30,
	0xe7, 0x54, 0x99, 0xa3, 0xad, 0x72, 0x9c, 0x26, 0xe6, 0x38, 0x62, 0xff, 0x2d, 0xc9, 0x2f, 0xb0,
	0x93, 0xf7, 0x12, 0x59, 0x1e, 0x43, 0x47, 0xba, 0x85, 0xc2, 0xcf, 0x18, 0xcb, 0x48, 0x23, 0xcf,
	0x45, 0x07, 0x60, 0x86, 0x11, 0xfd, 0x74, 0xc7, 0xd5, 0x4d, 0xae, 0x6e, 0x73, 0xc1, 0xc8, 0x73,
	0x9d, 0x6b, 0x70, 0xc6, 0x64, 0xe6, 0xc5, 0x8c, 0x44, 0xaf, 0x3f, 0x31, 0x12, 0x05, 0xd8, 0x3f,
	0x0b, 0x43, 0xdf, 0x9b, 0x62, 0xe6, 0xd1, 0xe0, 0x7e, 0xa5, 0x21, 0x04, 0xad, 0x10, 0xb3, 0x8f,
	0x3c, 0xb8, 0x39, 0xe6, 0xeb, 0x44, 0x86, 0xa3, 0x59, 0x6c, 0x19, 0x3d, 0x23, 0x91, 0x25, 0x6b,
	0xe7, 0x0d, 0x3c, 0xa9, 0x4d, 0x76, 0xcf, 0x13, 0x39, 0xbf, 0xc3, 0xee, 0x84, 0xb0, 0x31, 0xa5,
	0x6c, 0x84, 0xe3, 0xf8, 0x96, 0x46, 0xae, 0x2c, 0xb4, 0x07, 0x1d, 0xea, 0xbb, 0x52, 0x2a, 0x2a,
	0xd5, 0x45, 0x89, 0x45, 0x40, 0x6e, 0x95, 0x45, 0x5a, 0xb2, 0x2e, 0x72, 0x5e, 0xc0, 0x5e, 0x29,
	0xba, 0xa8, 0x6c, 0x07, 0xd6, 0x18, 0xbd, 0x26, 0x81, 0x08, 0x9c, 0x6e, 0x9c, 0x4b, 0x78, 0x28,
	0x1c, 0x5e, 0xdf, 0x60, 0xcf, 0x97, 0xb5, 0xd8, 0xd0, 0xa6, 0xbe, 0xcb, 0x45, 0xc2, 0x5e, 0xed,
	0x13, 0x5d, 0x40, 0x6e, 0x53, 0x5d, 0x5a, 0x82, 0xda, 0x3b, 0xcf, 0x60, 0x27, 0x1f, 0xae, 0x36,
	0xf9, 0x02, 0xd0, 0x84, 0x94, 0x70, 0x38, 0x04, 0x13, 0x4f, 0xa7, 0x74, 0x1e, 0xb0, 0xa1, 0xea,
	0x97, 0x12, 0x14, 0x51, 0x6a, 0xae, 0x44, 0xc9, 0x28, 0xa3, 0x74, 0xc2, 0x0f, 0x7d, 0x4f, 0x84,
	0x66, 0xf0, 0x60, 0x42, 0xf2, 0xe8, 0xd4, 0x57, 0xa8, 0x63, 0xd7, 0xac, 0xc1, 0xce, 0x28, 0x60,
	0x77, 0x0c, 0xdd, 0x2c, 0x51, 0x6d, 0x49, 0xff, 0x34, 0xe1, 0xd1, 0x68, 0xfe, 0xde, 0xf7, 0xe2,
	0x8f, 0x85, 0x77, 0x78, 0x08, 0xd9, 0xd5, 0x2e, 0xdf, 0xf5, 0x1e, 0x74, 0xc2, 0xd4, 0x8d, 0x44,
	0x43, 0x85, 0x9d, 0x26, 0x52, 0xaf, 0xc1, 0xd0, 0x5e, 0x43, 0x0f, 0x3a, 0xae, 0x37, 0xa5, 0xd1,
	0x82, 0x44, 0x77, 0x43, 0xd7, 0x6a, 0xa5, 0x5e, 0x9a, 0x08, 0x39, 0xb0, 0x19, 0x91, 0x90, 0xc6,
	0x1e, 0xa3, 0xdc, 0x64, 0x8d, 0x9b, 0xe4, 0x64, 0x3c, 0x0a, 0x89, 0xa7, 0x91, 0x17, 0x26, 0xef,
	0xc5, 0x5a, 0x17, 0x51, 0x32, 0x51, 0x82, 0xcd, 0x35, 0xb9, 0x4b, 0x3a, 0x12, 0x5b, 0x1b, 0xfc,
	0xe5, 0xa9, 0x3d, 0xb2, 0x60, 0x63, 0x41, 0xa2, 0x38, 0xf1, 0x6c, 0x73, 0x4f, 0xb9, 0x45, 0x27,
	0xd0, 0x0e, 0x7d, 0xcc, 0x3e, 0xd0, 0xe8, 0xc6, 0x32, 0x7b, 0x8d, 0xe3, 0xad, 0xfe, 0x83, 0xe7,
	0x29, 0x6f, 0x8f, 0x84, 0x78, 0xac, 0x0c, 0x9c, 0xef, 0xe0, 0xe0, 0x2a, 0xf4, 0x29, 0x76, 0x05,
	0x6c, 0x23, 0x3c, 0xbd, 0xc6, 0x33, 0x85, 0x1e, 0x82, 0x96, 0x8b, 0x19, 0xe6, 0xc0, 0x6d, 0x8e,
	0xf9, 0xda, 0xe9, 0xc3, 0x61, 0xb5, 0x8b, 0xe8, 0x90, 0x44, 0xac, 0x91, 0x21, 0xe6, 0x7c, 0x0b,
	0xbb, 0xc5, 0xf6, 0xac, 0xa0, 0xd5, 0xbf, 0x1a, 0xf0, 0x68, 0x18, 0xc4, 0x0c, 0xfb, 0x7e, 0xa1,
	0xa3, 0x05, 0xf4, 0x1b, 0x65, 0xf4, 0x73, 0x3d, 0x6f, 0xae, 0xe8, 0xb9, 0x51, 0xee, 0xb9, 0x86,
	0x6d, 0x2b, 0x87, 0x6d, 0x72, 0x8e, 0x62, 0x51, 0x2b, 0xce, 0x11, 0xc3, 0xde, 0x55, 0xe0, 0x55,
	0x1e, 0xe4, 0x73, 0xaf, 0xa6, 0x56, 0xa6, 0x91, 0x2f, 0xb3, 0x0f, 0x56, 0x39, 0xe9, 0x8a, 0x42,
	0xcf, 0xc1, 0x7a, 0x45, 0x42, 0x9f, 0xde, 0x55, 0x7c, 0x31, 0x10, 0xb4, 0x02, 0x7c, 0x43, 0x64,
	0x4b, 0x93, 0xb5, 0xba, 0x1a, 0x4d, 0xed, 0x6a, 0x0c, 0x60, 0xbf, 0x22, 0x46, 0x7d, 0xe2, 0xa7,
	0xdf, 0x43, 0x5b, 0x5e, 0x4c, 0xd4, 0x81, 0x8d, 0x9f, 0x87, 0x6f, 0xaf, 0xde, 0x0d, 0xfa, 0xdd,
	0x2f, 0xd4, 0xe6, 0xe5, 0x69, 0xb7, 0x81, 0x4c, 0x58, 0xfb, 0x75, 0xf8, 0x76, 0xd0, 0xef, 0x36,
	0xc5, 0xf2, 0xe5, 0x69, 0xd7, 0xe8, 0xff, 0x6d, 0xc2, 0xe6, 0x59, 0x72, 0xb7, 0xc5, 0x29, 0xd1,
	0x88, 0x73, 0x93, 0x4e, 0xf7, 0xe8, 0x48, 0xdc, 0xfe, 0xea, 0x8f, 0x8c, 0xfd, 0xd5, 0x32, 0xb5,
	0x28, 0xfb, 0x02, 0x36, 0x75, 0x02, 0x47, 0x76, 0xde, 0x5e, 0xa7, 0x41, 0xfb, 0xa0, 0x52, 0x27,
	0x02, 0xbd, 0x82, 0x8e, 0xc6, 0xb1, 0x68, 0x3f, 0xb3, 0x2d, 0x96, 0x64, 0x57, 0xa9, 0x44, 0x94,
	0x1f, 0xa0, 0x2d, 0x39, 0x11, 0xed, 0x66, 0x76, 0xb9, 0x32, 0xf6, 0x4a, 0x72, 0xe1, 0xfc, 0x23,
	0x98, 0x6a, 0x2e, 0x43, 0xd2, 0xaa, 0x38, 0xbd, 0xd9, 0x56, 0x59, 0x21, 0xfc, 0xcf, 0xe1, 0xcb,
	0x0b, 0xc2, 0xde, 0xcc, 0x7d, 0xff, 0xff, 0xc7, 0x38, 0x03, 0xc8, 0x26, 0x38, 0x24, 0xed, 0x4a,
	0x13, 0xa0, 0xbd, 0x5f, 0xa1, 0xd1, 0x90, 0xcc, 0x26, 0xb4, 0x0c, 0xc9, 0xd2, 0xa8, 0x97, 0x21,
	0x59, 0x31, 0xd0, 0x25, 0x8d, 0xd5, 0x46, 0xb0, 0xac, 0xb1, 0xe5, 0x69, 0x2e, 0x6b, 0x6c, 0xd5,
	0xcc, 0x86, 0x61, 0xa7, 0x8a, 0x10, 0x91, 0x23, 0x9c, 0x6a, 0x08, 0xd6, 0x7e, 0x52, 0x6b, 0x93,
	0x26, 0x38, 0x6e, 0xa0, 0x4b, 0xd8, 0xca, 0xf3, 0x27, 0x3a, 0x94, 0x9c, 0x5e, 0xf5, 0xd5, 0xb3,
	0x8f, 0x96, 0x68, 0x45, 0xc5, 0x97, 0xb0, 0x95, 0xa7, 0x31, 0x15, 0xae, 0x92, 0x72, 0x55, 0xb8,
	0x25, 0xdc, 0x37, 0x81, 0x6e, 0x91, 0x6e, 0x90, 0x7c, 0x56, 0x4b, 0xc8, 0xcf, 0x7e, 0xbc, 0x54,
	0x2f, 0x82, 0x32, 0x38, 0xa8, 0x19, 0x2f, 0xd1, 0xd7, 0xc2, 0x7f, 0xf5, 0xbc, 0x6b, 0x3f, 0xbd,
	0x8f, 0xa9, 0xc8, 0xfa, 0x0e, 0xb6, 0x4b, 0x0c, 0x86, 0x64, 0xad, 0xcb, 0xf8, 0xd1, 0xee, 0x2d,
	0x37, 0x90, 0x2d, 0x3c, 0xdf, 0xf8, 0x2d, 0xfd, 0xc3, 0xf4, 0x7e, 0x9d, 0xff, 0x7d, 0x1a, 0xfc,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x10, 0xa4, 0xff, 0x55, 0x53, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	//Set the root password
	SetRootPassword(ctx context.Context, in *SetRootPasswordRequest, opts ...grpc.CallOption) (*SetRootPasswordResponse, error)
	//Set the root email
	SetRootEmail(ctx context.Context, in *SetRootEmailRequest, opts ...grpc.CallOption) (*SetRootEmailResponse, error)
	//Set the account password
	SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*SetPasswordResponse, error)
	//Set the account email
	SetEmail(ctx context.Context, in *SetEmailRequest, opts ...grpc.CallOption) (*SetEmailResponse, error)
	// Return configuration whitout all detail, no needed to be secure.
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// Return the configuration with all detail, must be secure.
	GetFullConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// Save a service configuration
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error)
	// Stop a service
	StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*StopServiceResponse, error)
	// Start a service
	StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*StartServiceResponse, error)
	// Create and upload service package
	UploadServicePackage(ctx context.Context, opts ...grpc.CallOption) (AdminService_UploadServicePackageClient, error)
	// Publish a service...
	PublishService(ctx context.Context, in *PublishServiceRequest, opts ...grpc.CallOption) (*PublishServiceResponse, error)
	// Install a service...
	InstallService(ctx context.Context, in *InstallServiceRequest, opts ...grpc.CallOption) (*InstallServiceResponse, error)
	// Uninstall a service...
	UninstallService(ctx context.Context, in *UninstallServiceRequest, opts ...grpc.CallOption) (*UninstallServiceResponse, error)
	// Register external service to be start by Globular in order to run
	// as exemple MongoDB and Prometheus.
	RegisterExternalApplication(ctx context.Context, in *RegisterExternalApplicationRequest, opts ...grpc.CallOption) (*RegisterExternalApplicationResponse, error)
	// Deloyed a web application to a globular node.
	DeployApplication(ctx context.Context, opts ...grpc.CallOption) (AdminService_DeployApplicationClient, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) SetRootPassword(ctx context.Context, in *SetRootPasswordRequest, opts ...grpc.CallOption) (*SetRootPasswordResponse, error) {
	out := new(SetRootPasswordResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/SetRootPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetRootEmail(ctx context.Context, in *SetRootEmailRequest, opts ...grpc.CallOption) (*SetRootEmailResponse, error) {
	out := new(SetRootEmailResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/SetRootEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*SetPasswordResponse, error) {
	out := new(SetPasswordResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/SetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetEmail(ctx context.Context, in *SetEmailRequest, opts ...grpc.CallOption) (*SetEmailResponse, error) {
	out := new(SetEmailResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/SetEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetFullConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/GetFullConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigResponse, error) {
	out := new(SaveConfigResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/SaveConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*StopServiceResponse, error) {
	out := new(StopServiceResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/StopService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*StartServiceResponse, error) {
	out := new(StartServiceResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/StartService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UploadServicePackage(ctx context.Context, opts ...grpc.CallOption) (AdminService_UploadServicePackageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdminService_serviceDesc.Streams[0], "/admin.AdminService/UploadServicePackage", opts...)
	if err != nil {
		return nil, err
	}
	x := &adminServiceUploadServicePackageClient{stream}
	return x, nil
}

type AdminService_UploadServicePackageClient interface {
	Send(*UploadServicePackageRequest) error
	CloseAndRecv() (*UploadServicePackageResponse, error)
	grpc.ClientStream
}

type adminServiceUploadServicePackageClient struct {
	grpc.ClientStream
}

func (x *adminServiceUploadServicePackageClient) Send(m *UploadServicePackageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *adminServiceUploadServicePackageClient) CloseAndRecv() (*UploadServicePackageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadServicePackageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *adminServiceClient) PublishService(ctx context.Context, in *PublishServiceRequest, opts ...grpc.CallOption) (*PublishServiceResponse, error) {
	out := new(PublishServiceResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/PublishService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) InstallService(ctx context.Context, in *InstallServiceRequest, opts ...grpc.CallOption) (*InstallServiceResponse, error) {
	out := new(InstallServiceResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/InstallService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UninstallService(ctx context.Context, in *UninstallServiceRequest, opts ...grpc.CallOption) (*UninstallServiceResponse, error) {
	out := new(UninstallServiceResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/UninstallService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RegisterExternalApplication(ctx context.Context, in *RegisterExternalApplicationRequest, opts ...grpc.CallOption) (*RegisterExternalApplicationResponse, error) {
	out := new(RegisterExternalApplicationResponse)
	err := c.cc.Invoke(ctx, "/admin.AdminService/RegisterExternalApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeployApplication(ctx context.Context, opts ...grpc.CallOption) (AdminService_DeployApplicationClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AdminService_serviceDesc.Streams[1], "/admin.AdminService/DeployApplication", opts...)
	if err != nil {
		return nil, err
	}
	x := &adminServiceDeployApplicationClient{stream}
	return x, nil
}

type AdminService_DeployApplicationClient interface {
	Send(*DeployApplicationRequest) error
	CloseAndRecv() (*DeployApplicationResponse, error)
	grpc.ClientStream
}

type adminServiceDeployApplicationClient struct {
	grpc.ClientStream
}

func (x *adminServiceDeployApplicationClient) Send(m *DeployApplicationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *adminServiceDeployApplicationClient) CloseAndRecv() (*DeployApplicationResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DeployApplicationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	//Set the root password
	SetRootPassword(context.Context, *SetRootPasswordRequest) (*SetRootPasswordResponse, error)
	//Set the root email
	SetRootEmail(context.Context, *SetRootEmailRequest) (*SetRootEmailResponse, error)
	//Set the account password
	SetPassword(context.Context, *SetPasswordRequest) (*SetPasswordResponse, error)
	//Set the account email
	SetEmail(context.Context, *SetEmailRequest) (*SetEmailResponse, error)
	// Return configuration whitout all detail, no needed to be secure.
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// Return the configuration with all detail, must be secure.
	GetFullConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// Save a service configuration
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigResponse, error)
	// Stop a service
	StopService(context.Context, *StopServiceRequest) (*StopServiceResponse, error)
	// Start a service
	StartService(context.Context, *StartServiceRequest) (*StartServiceResponse, error)
	// Create and upload service package
	UploadServicePackage(AdminService_UploadServicePackageServer) error
	// Publish a service...
	PublishService(context.Context, *PublishServiceRequest) (*PublishServiceResponse, error)
	// Install a service...
	InstallService(context.Context, *InstallServiceRequest) (*InstallServiceResponse, error)
	// Uninstall a service...
	UninstallService(context.Context, *UninstallServiceRequest) (*UninstallServiceResponse, error)
	// Register external service to be start by Globular in order to run
	// as exemple MongoDB and Prometheus.
	RegisterExternalApplication(context.Context, *RegisterExternalApplicationRequest) (*RegisterExternalApplicationResponse, error)
	// Deloyed a web application to a globular node.
	DeployApplication(AdminService_DeployApplicationServer) error
}

// UnimplementedAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (*UnimplementedAdminServiceServer) SetRootPassword(ctx context.Context, req *SetRootPasswordRequest) (*SetRootPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRootPassword not implemented")
}
func (*UnimplementedAdminServiceServer) SetRootEmail(ctx context.Context, req *SetRootEmailRequest) (*SetRootEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRootEmail not implemented")
}
func (*UnimplementedAdminServiceServer) SetPassword(ctx context.Context, req *SetPasswordRequest) (*SetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}
func (*UnimplementedAdminServiceServer) SetEmail(ctx context.Context, req *SetEmailRequest) (*SetEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEmail not implemented")
}
func (*UnimplementedAdminServiceServer) GetConfig(ctx context.Context, req *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (*UnimplementedAdminServiceServer) GetFullConfig(ctx context.Context, req *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullConfig not implemented")
}
func (*UnimplementedAdminServiceServer) SaveConfig(ctx context.Context, req *SaveConfigRequest) (*SaveConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveConfig not implemented")
}
func (*UnimplementedAdminServiceServer) StopService(ctx context.Context, req *StopServiceRequest) (*StopServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopService not implemented")
}
func (*UnimplementedAdminServiceServer) StartService(ctx context.Context, req *StartServiceRequest) (*StartServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartService not implemented")
}
func (*UnimplementedAdminServiceServer) UploadServicePackage(srv AdminService_UploadServicePackageServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadServicePackage not implemented")
}
func (*UnimplementedAdminServiceServer) PublishService(ctx context.Context, req *PublishServiceRequest) (*PublishServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishService not implemented")
}
func (*UnimplementedAdminServiceServer) InstallService(ctx context.Context, req *InstallServiceRequest) (*InstallServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallService not implemented")
}
func (*UnimplementedAdminServiceServer) UninstallService(ctx context.Context, req *UninstallServiceRequest) (*UninstallServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UninstallService not implemented")
}
func (*UnimplementedAdminServiceServer) RegisterExternalApplication(ctx context.Context, req *RegisterExternalApplicationRequest) (*RegisterExternalApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterExternalApplication not implemented")
}
func (*UnimplementedAdminServiceServer) DeployApplication(srv AdminService_DeployApplicationServer) error {
	return status.Errorf(codes.Unimplemented, "method DeployApplication not implemented")
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_SetRootPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRootPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetRootPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/SetRootPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetRootPassword(ctx, req.(*SetRootPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetRootEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRootEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetRootEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/SetRootEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetRootEmail(ctx, req.(*SetRootEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/SetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetPassword(ctx, req.(*SetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/SetEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetEmail(ctx, req.(*SetEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetFullConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetFullConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/GetFullConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetFullConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/SaveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/StopService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StopService(ctx, req.(*StopServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/StartService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartService(ctx, req.(*StartServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UploadServicePackage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdminServiceServer).UploadServicePackage(&adminServiceUploadServicePackageServer{stream})
}

type AdminService_UploadServicePackageServer interface {
	SendAndClose(*UploadServicePackageResponse) error
	Recv() (*UploadServicePackageRequest, error)
	grpc.ServerStream
}

type adminServiceUploadServicePackageServer struct {
	grpc.ServerStream
}

func (x *adminServiceUploadServicePackageServer) SendAndClose(m *UploadServicePackageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *adminServiceUploadServicePackageServer) Recv() (*UploadServicePackageRequest, error) {
	m := new(UploadServicePackageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AdminService_PublishService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PublishService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/PublishService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PublishService(ctx, req.(*PublishServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_InstallService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).InstallService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/InstallService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).InstallService(ctx, req.(*InstallServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UninstallService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UninstallService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/UninstallService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UninstallService(ctx, req.(*UninstallServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RegisterExternalApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterExternalApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RegisterExternalApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.AdminService/RegisterExternalApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RegisterExternalApplication(ctx, req.(*RegisterExternalApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeployApplication_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdminServiceServer).DeployApplication(&adminServiceDeployApplicationServer{stream})
}

type AdminService_DeployApplicationServer interface {
	SendAndClose(*DeployApplicationResponse) error
	Recv() (*DeployApplicationRequest, error)
	grpc.ServerStream
}

type adminServiceDeployApplicationServer struct {
	grpc.ServerStream
}

func (x *adminServiceDeployApplicationServer) SendAndClose(m *DeployApplicationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *adminServiceDeployApplicationServer) Recv() (*DeployApplicationRequest, error) {
	m := new(DeployApplicationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRootPassword",
			Handler:    _AdminService_SetRootPassword_Handler,
		},
		{
			MethodName: "SetRootEmail",
			Handler:    _AdminService_SetRootEmail_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _AdminService_SetPassword_Handler,
		},
		{
			MethodName: "SetEmail",
			Handler:    _AdminService_SetEmail_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _AdminService_GetConfig_Handler,
		},
		{
			MethodName: "GetFullConfig",
			Handler:    _AdminService_GetFullConfig_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _AdminService_SaveConfig_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _AdminService_StopService_Handler,
		},
		{
			MethodName: "StartService",
			Handler:    _AdminService_StartService_Handler,
		},
		{
			MethodName: "PublishService",
			Handler:    _AdminService_PublishService_Handler,
		},
		{
			MethodName: "InstallService",
			Handler:    _AdminService_InstallService_Handler,
		},
		{
			MethodName: "UninstallService",
			Handler:    _AdminService_UninstallService_Handler,
		},
		{
			MethodName: "RegisterExternalApplication",
			Handler:    _AdminService_RegisterExternalApplication_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadServicePackage",
			Handler:       _AdminService_UploadServicePackage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DeployApplication",
			Handler:       _AdminService_DeployApplication_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "admin/admin.proto",
}
