apiVersion: apps/v1
kind: Deployment
metadata:
 name: globular-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: globular-v1
 template:
  metadata:
   labels:
    app: globular-v1
  spec:
   containers:
    - name: globular-node
      image: globular/globular:latest
      volumeMounts:
       - mountPath: /globular/config
         name: config-volume
       - mountPath: /globular/data
         name: data-volume
       - mountPath: /globular/webroot
         name: webroot-volume
      command: [ "./Globular" ]
      resources:
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits:
        memory: "250Mi"
        cpu: "500m"
   volumes:
    - name: config-volume
      persistentVolumeClaim:
       claimName: globular-config-volume-claim
    - name: data-volume
      persistentVolumeClaim:
       claimName: globular-data-volume-claim
    - name: webroot-volume 
      persistentVolumeClaim:
       claimName: globular-webroot-volume-claim