apiVersion: v1

# The configuration directory
kind: PersistentVolumeClaim
metadata:
 name: globular-config-volume-claim
spec:
 volumeName: globular-config-volume
 accessModes:
  - ReadWriteOnce
 storageClassName: standard
 resources:
  requests:
   storage: 10Mi
---

apiVersion: v1

# The data directory
kind: PersistentVolumeClaim
metadata:
 name: globular-data-volume-claim
spec:
 volumeName: globular-data-volume
 accessModes:
  - ReadWriteOnce
 storageClassName: standard  
 resources:
  requests:
   storage: 128Gi
---

apiVersion: v1

# The web server directory
kind: PersistentVolumeClaim
metadata:
 name: globular-webroot-volume-claim
spec:
 volumeName: globular-webroot-volume
 accessModes:
  - ReadWriteOnce
 storageClassName: standard
 resources:
  requests:
   storage: 64Gi