apiVersion: v1

#  The configuration directory
kind: PersistentVolume
metadata:
 name: globular-config-volume
spec:
 capacity:
  storage: 10Mi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
  #- ReadOnlyMany not availble for hostPath...
  #- ReadWriteMany
 storageClassName: standard
 hostPath:
  path: /globular/config
  type: DirectoryOrCreate
---

apiVersion: v1

# The data directrory
kind: PersistentVolume
metadata:
 name: globular-data-volume
spec:
 capacity:
  storage: 128Gi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
 storageClassName: standard
 hostPath:
  path: /globular/data
  type: DirectoryOrCreate
---

apiVersion: v1
 
# The web server directrory
kind: PersistentVolume
metadata:
 name: globular-webroot-volume
spec:
 capacity:
  storage: 64Gi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
 storageClassName: standard 
 hostPath:
  path: /globular/webroot
  type: DirectoryOrCreate